### PR TITLE
Fixed SA1130 code fix for return statements and arrow expression clauses

### LINKED ISSUE #2902: SA1130 Delegate to lambda syntax CodeFixProvider crash
Example code

```
        private static EventHandler CatchError(ToolStripItem item, Action action)
        {
            return delegate
            {
                try
                {
                    action();
                }
                catch (Exception ex)
                {
                    throw new MyException($"Failed executing {item.Text}: {ex.Message}");
                }
            };
        }
```

Stack trace

```System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Immutable.ImmutableArray`1.GetEnumerator()
   at StyleCop.Analyzers.ReadabilityRules.SA1130CodeFixProvider.GenerateUniqueParameterNames(SemanticModel semanticModel,AnonymousMethodExpressionSyntax anonymousMethod,ImmutableArray`1 argumentNames)
   at StyleCop.Analyzers.ReadabilityRules.SA1130CodeFixProvider.ReplaceWithLambda(SemanticModel semanticModel,AnonymousMethodExpressionSyntax anonymousMethod)
   at async StyleCop.Analyzers.ReadabilityRules.SA1130CodeFixProvider.CanFixAsync(<Unknown Parameters>)
   at async StyleCop.Analyzers.ReadabilityRules.SA1130CodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

### PR DESCRIPTION
**Pull request by vweijsters**
Fixes #2902

### CODE REVIEW

**Comment by sharwell** [comment]
💡 Can you add an additional test for an event with an initializer? I don't think it's going to change anything but it seems like a test gap:

```csharp
public static event EventHandler StaticEvent = delegate { };
public event EventHandler InstanceEvent = delegate { };
```

File: StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1130CodeFixProvider.cs [hunk 1]
```diff
@@ -193,6 +201,14 @@ private static ImmutableArray<string> GetEqualsArgumentList(SemanticModel semant
             return namedTypeSymbol.DelegateInvokeMethod.Parameters.Select(ps => ps.Name).ToImmutableArray();
         }
 
+        private static ImmutableArray<string> GetMemberReturnTypeArgumentList(SemanticModel semanticModel, AnonymousMethodExpressionSyntax anonymousMethod)
+        {
+            var enclosingSymbol = semanticModel.GetEnclosingSymbol(anonymousMethod.Parent.SpanStart);
+            var returnType = (INamedTypeSymbol)((IMethodSymbol)enclosingSymbol).ReturnType;
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1130CodeFixProvider.cs]: ❓ Will the cast to `INamedTypeSymbol` fail for invalid code like this?

```csharp
public static EventHandler[] TestMethod2() => delegate { };
```

Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1130CodeFixProvider.cs]: ❓ Will the cast to `IMethodSymbol` fail for local functions?

```csharp
void Method() {
  EventHandler LocalFunction() => delegate { };
}
```

Comment (vweijsters) [reply StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1130CodeFixProvider.cs]: This fails, I will fix it.

Comment (vweijsters) [reply StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1130CodeFixProvider.cs]: It won't.

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1130UnitTests.cs [hunk 2]
```diff
@@ -710,5 +710,135 @@ static void Main(string[] args)
...
+            };
+
+            var test = new CSharpTest
+            {
+                TestCode = testCode,
+                FixedCode = testCode,
+            };
+
+            test.ExpectedDiagnostics.AddRange(expected);
+            test.RemainingDiagnostics.AddRange(expected);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1130UnitTests.cs]: 📝 This line should not be necessary in the latest versions of the test framework. It will automatically propagate `ExpectedDiagnostics` to `RemainingDiagnostics` since the code fix did not make any changes.

```suggestion
```

**Comment by sharwell** [comment]
@vweijsters You feeling confident about this one now? 😄

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1130UnitTests.cs (hunk 2 above)
Comment (vweijsters) [reply StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1130UnitTests.cs]: Apparently the version used in the stabilization branch is too old. Your change breaks the build 😞

Comment (vweijsters) [reply StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1130UnitTests.cs]: I've removed the suggested change

**Comment by vweijsters** [comment]
Should be OK now, but I'm not betting anything on it 😉
