### PR TITLE
Relax documentation requirements according to the current settings

### LINKED ISSUE #1731: Documentation rules inside of setting file not working
Hi, 

I tried to use the option of not requiring documentation of internal members as instructed in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md

``` csharp
 "documentationRules": {
      "documentInterfaces": true,
      "documentInternalMembers": false
    }
```

However, it does not work. I closed visual studio and re-opened it. Added the file to additional files but, none of them worked. 
Even this element is not defined in the schema.

### LINKED ISSUE #2443: SA1604 reported for non-exposed members even when documentInternalElements is false
When the `documentInternalElements` or `documentPrivateElements` option is set to false, SA1604:ElementDocumentationMustHaveSummary should never be reported for those non-public members which are exempted from the documentation requirement. As expected, there is no reported violation for:

```
private int Foo()
```

However, it _is_ reported in the following examples:

```
///
private int Foo()
```

```
/**
 *
 */
private int Foo()
```

### LINKED ISSUE #2444: SA1611 reported for non-exposed members even when documentInternalElements is false
When the `documentInternalElements` or `documentPrivateElements` option is set to false, SA1611:ElementParametersMustBeDocumented should never be reported for those non-public members which are exempted from the documentation requirement. As expected, there is no reported violation for:

```
private int Foo(int arg)
```

However, it _is_ reported in the following examples:

```
///
private int Foo(int arg)
```

```
/**
 *
 */
private int Foo(int arg)
```

### LINKED ISSUE #2445: SA1615 reported for non-exposed members even when documentInternalElements is false
When the `documentInternalElements` or `documentPrivateElements` option is set to false, SA1615:ElementReturnValueMustBeDocumented should never be reported for those non-public members which are exempted from the documentation requirement. As expected, there is no reported violation for:

```
private int Foo()
```

However, it _is_ reported in the following examples:

```
///
private int Foo()
```

```
/**
 *
 */
private int Foo()
```

### LINKED ISSUE #2446: SA1618 reported for non-exposed members even when documentInternalElements is false
When the `documentInternalElements` or `documentPrivateElements` option is set to false, SA1618:GenericTypeParametersMustBeDocumented should never be reported for those non-public members which are exempted from the documentation requirement. As expected, there is no reported violation for:

```
private T Foo<T>()
```

However, it _is_ reported in the following examples:

```
///
private T Foo<T>()
```

```
/**
 *
 */
private T Foo<T>()
```

### LINKED ISSUE #2450: SA1605 reported for non-exposed members even when documentInternalElements is false
:memo: I observed that the issue reported in #2443 also affects SA1605.

### LINKED ISSUE #2451: SA1609 reported for non-exposed members even when documentInternalElements is false
:memo: This is similar to #2443, but affects SA1609.

### LINKED ISSUE #2452: SA1612 reported for non-exposed members even when documentInternalElements is false
:memo: This is similar to #2443 but affects SA1612.

### LINKED ISSUE #2453: SA1619 reported for non-exposed members even when documentInternalElements is false
:memo: This is similar to #2443 but affects SA1619.

### PR DESCRIPTION
**Pull request by sharwell**
* Fixes #1731 (incorrect documentation of `documentInternalElements`)
* Fixes #2443 
* Fixes #2444 
* Fixes #2445 
* Fixes #2446
* Fixes #2450 
* Fixes #2451 
* Fixes #2452
* Fixes #2453

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1611ElementParametersMustBeDocumented.cs [hunk 1]
```diff
@@ -69,8 +75,13 @@ protected override void HandleXmlElement(SyntaxNodeAnalysisContext context, IEnu
         }
 
         /// <inheritdoc/>
-        protected override void HandleCompleteDocumentation(SyntaxNodeAnalysisContext context, XElement completeDocumentation, params Location[] diagnosticLocations)
+        protected override void HandleCompleteDocumentation(SyntaxNodeAnalysisContext context, bool needsComment, XElement completeDocumentation, params Location[] diagnosticLocations)
         {
+            if (!needsComment)
+            {
+                // Omitting documentation for a parameter is allowed for this element.
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1611ElementParametersMustBeDocumented.cs]: ❗️ Missing return statement here

Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1611ElementParametersMustBeDocumented.cs]: ➡️  now fixed
