### PR TITLE
Implement a code fix for SA1609 and SA1610

### LINKED ISSUE #534: Code fix: SA1610 (PropertyDocumentationMustHaveValueText)
Implement a code fix for #130.

Normally it is not possible to generate the text for a documentation element. However, in many cases where the `<summary>` text for a property follows a particular form (e.g. the form prescribed in #143 and #144), the `<value>` text can be filled in using a slightly reworded variant of the summary text. A concrete example of this, although targeted to the documentation requirements of a particular SDK, can be seen in openstacknetsdk/OpenStackNetAnalyzers#6.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #534

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs [hunk 1]
```diff
@@ -0,0 +1,199 @@
...
+                        if (index >= 0)
+                            valueText = valueText.Remove(index, prefix.Length);
+
+                        SyntaxToken replaced = SyntaxFactory.Token(getsToken.LeadingTrivia, getsToken.Kind(), text, valueText, getsToken.TrailingTrivia);
+                        summaryContent = summaryContent.Replace(firstText, firstText.ReplaceToken(getsToken, replaced));
+                        return true;
+                    }
+                }
+            }
+
```
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs]: :point_up: The nested if statements above are not inline with the rest of the code, where an return as quickly as possible strategy is used.

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs [hunk 2]
```diff
@@ -0,0 +1,199 @@
...
+                return document;
+
+            SyntaxList<XmlNodeSyntax> summaryContent = summaryElement.Content;
+            if (!this.TryRemoveSummaryPrefix(ref summaryContent, "Gets or sets "))
+            {
+                if (!this.TryRemoveSummaryPrefix(ref summaryContent, "Gets "))
+                {
+                    this.TryRemoveSummaryPrefix(ref summaryContent, "Sets ");
+                }
+            }
```
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs]: I don't particularly like the ref parameters in `TryRemoveSummaryPrefix` calls. It is not similar to the Roslyn API, where each transforming method returns the modified node.

I'd prefer to see something like:
`summaryContent = this.TryRemoveSummaryPrefix(summaryContent, "Gets or sets ", "Gets ", "Sets ")`

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs [hunk 3]
```diff
@@ -0,0 +1,199 @@
...
+                    {
+                        string text = getsToken.Text;
+                        string valueText = getsToken.ValueText;
+                        int index = text.IndexOf(prefix);
+                        if (index >= 0)
+                        {
+                            bool additionalCharacters = index + prefix.Length < text.Length;
+                            text = text.Substring(0, index)
+                                + (additionalCharacters ? char.ToUpperInvariant(text[index + prefix.Length]).ToString() : string.Empty)
+                                + text.Substring(index + (additionalCharacters ? (prefix.Length + 1) : prefix.Length));
```
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs]: This will throw an `ArgumentOutOfRangeException` if there is only a single character after the prefix. For example: `Gets x`

File: StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DocumentationCommentExtensions.cs [hunk 4]
```diff
@@ -0,0 +1,190 @@
...
+                            firstTextToken.ValueText.TrimStart(),
+                            firstTextToken.TrailingTrivia);
+
+                        summaryContent = summaryContent.Replace(firstTextSyntax, firstTextSyntax.ReplaceToken(firstTextToken, newFirstToken));
+                    }
+                }
+            }
+
+            return summaryContent;
+        }
```
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DocumentationCommentExtensions.cs]: :point_up: The method name does not cover the functionality of the method. It potentially removes more than just the first and last empty line.

File: StyleCop.Analyzers/StyleCop.Analyzers/Helpers/XmlSyntaxFactory.cs [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+            return TextNewLine(true);
+        }
+
+        public static SyntaxToken TextNewLine(bool continueComment)
+        {
+            SyntaxToken token = SyntaxFactory.XmlTextNewLine(
+                SyntaxFactory.TriviaList(),
+                Environment.NewLine,
+                Environment.NewLine,
+                SyntaxFactory.TriviaList());
```
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/XmlSyntaxFactory.cs]: The code above should use `FormattingOptions.NewLine` instead of `Environment.NewLine`, to keep in line with the new line style used in a project / solution.

**Comment by vweijsters** [comment]
Besides the remarks above, the code looks good :+1: 

@sharwell When there is no properly formatted `<summary>` tag, I think it would be better to generate a `<value>` tag with a placeholder that contains the name of the property. What are your thoughts on that?

File: StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DocumentationCommentExtensions.cs (hunk 4 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DocumentationCommentExtensions.cs]: Hm. Perhaps it should trim all leading and trailing whitespace?

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs (hunk 3 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs]: I don't see it?

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs (hunk 2 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs]: How would you know whether or not to try the next prefix?

File: StyleCop.Analyzers/StyleCop.Analyzers/Helpers/XmlSyntaxFactory.cs (hunk 5 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/XmlSyntaxFactory.cs]: It should actually use the line ending of the current document, even if that differs from both of the above. Unfortunately I don't know how to get that.

Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/XmlSyntaxFactory.cs]: For better or worse, according to dotnet/roslyn#202 the behavior implemented here matches Roslyn's current formatting behavior.

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs (hunk 2 above)
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs]: You can't from the return value for sure. That's why I added all the possible prefixes as parameters to the call and they should then match in left to right order I guess.

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs (hunk 3 above)
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs]: My bad, I mistakenly assumed that string.Substring() will throw an exception when the start index is equal to the length, which isn't the case. It only throws that exception when the start index is larger than the length.

File: StyleCop.Analyzers/StyleCop.Analyzers/Helpers/XmlSyntaxFactory.cs (hunk 5 above)
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/XmlSyntaxFactory.cs]: That's not possible afaik and might even present a problem if someone is mixing different types of line endings in one document.

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/XmlSyntaxFactory.cs]: The issue is has a milestone assigned to it, so I guess they will be fixing it before release.
If they do fix it, I think the `FormattingOptions.NewLine` is the way to go.

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs (hunk 2 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs]: I prefer it the way its written, but that just means we should get more eyes on it. @pdelvo and @macpak what do you think?

**Comment by sharwell** [comment]
> When there is no properly formatted `<summary>` tag, I think it would be better to generate a `<value>` tag with a placeholder that contains the name of the property. What are your thoughts on that?

Can you give an example of what it currently does, and what you're thinking could be preferable?

File: StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DocumentationCommentExtensions.cs (hunk 4 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DocumentationCommentExtensions.cs]: @vweijsters This method was tough to write considering the way trivia works within documentation comments. When I used this in practice, it did a remarkably good job of inserting exactly the text I wanted to see. If you aren't opposed to it, I think I'd like to file a new issue to revisit the behavior in the future.

That said, I have no objection to renaming it, although I'm not sure exactly what to call it.

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DocumentationCommentExtensions.cs]: @sharwell I can't really think of a better name as well. 
As far as I'm concerned there is no need to revisit the behavior. I would prefer documentation for the method that explains the additional behavior, so that its clear for other developers reading the code that the method does more than the name implies.

**Comment by vweijsters** [comment]
Never mind about my suggestion above. I was typing an example to show what I meant and when I had it done, it looked worse than the current solution.

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs (hunk 2 above)
Comment (macpak) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1609SA1610CodeFixProvider.cs]: I'd keep @sharwell 's approach, mostly because for me the code is more readable.
