### PR TITLE
Make code fixes lazy

### LINKED ISSUE #529: Make code fixes lazy
Roslyn updated the api so that code fixes can be implemented to be lazy so that wether or not a code fix could be offered can be  seperated from actually creating the code fix.
Currently we are not really doing that. Instead we are precalculating the code fix when roslyn figures out if there is one or not.

Im working on this.

### PR DESCRIPTION
**Pull request by pdelvo**
I reworked all code fixes to increase performace.

They will now create the changed document only if they are requested to do so.

I also moved the GetSyntaxRootAsync out of the loop because it is not dependant on the diagnostic. I also noticed that GetSyntaxRootAsync was called twice in a code fix so I tidied that up too.

So most of this is just moving stuff around.

Fixes #529

### CODE REVIEW

**Comment by sharwell** [comment]
Solid work. Keep in mind that I have local copy of the code I reviewed, so please try to limit the scope of your changes in addressing my comments as I'll have to re-review each part that changed. My comments in the diff will be verbose, but that will help me track progress on addressing them. I'll also be including some general notes in a comment at the end.

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1642SA1643CodeFixProvider.cs [hunk 1]
```diff
@@ -39,58 +40,66 @@ public override FixAllProvider GetFixAllProvider()
...
-                var classDeclaration = node.FirstAncestorOrSelf<ClassDeclarationSyntax>();
-                var declarationSyntax = node.FirstAncestorOrSelf<BaseMethodDeclarationSyntax>();
 
-                ImmutableArray<string> standardText;
-                if (declarationSyntax is ConstructorDeclarationSyntax)
+                context.RegisterCodeFix(CodeAction.Create("Add standard text.", token => GetTransformedDocument(context, root, node)), diagnostic);
+            }
+        }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, XmlElementSyntax node)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1642SA1643CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback. Its `CancellationToken` property and `RegisterCodeFix` method are not valid at this time and it would be too easy to mistakenly use them.

File: StyleCop.Analyzers/StyleCop.Analyzers/LayoutRules/SA1517CodeFixProvider.cs [hunk 2]
```diff
@@ -30,32 +31,39 @@ public override FixAllProvider GetFixAllProvider()
...
             foreach (Diagnostic diagnostic in context.Diagnostics.Where(d => FixableDiagnostics.Contains(d.Id)))
             {
-                var syntaxRoot = await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(false);
+                context.RegisterCodeFix(CodeAction.Create("Remove blank lines at the start of the file", token => GetTransformedDocument(context, token)), diagnostic);
+            }
+
+            return Task.FromResult(true);
+        }
+
+        private static async Task<Document> GetTransformedDocument(CodeFixContext context, CancellationToken token)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/LayoutRules/SA1517CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/LayoutRules/SA1518CodeFixProvider.cs [hunk 3]
```diff
@@ -30,23 +31,30 @@ public override FixAllProvider GetFixAllProvider()
...
             {
-                var syntaxRoot = await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(false);
+                context.RegisterCodeFix(CodeAction.Create("Remove blank lines at the end of the file", token => GetTransformedDocument(context, token)), diagnostic);
+            }
+
+            return Task.FromResult(true);
+        }
 
-                var lastToken = syntaxRoot.GetLastToken(includeZeroWidth: true);
+        private static async Task<Document> GetTransformedDocument(CodeFixContext context, CancellationToken token)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/LayoutRules/SA1518CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1119CodeFixProvider.cs [hunk 4]
```diff
@@ -36,34 +36,40 @@ public override FixAllProvider GetFixAllProvider()
...
+                    context.RegisterCodeFix(CodeAction.Create("Remove parenthesis", token => GetTransformedDocument(context, root, syntax)), diagnostic);
+                }
+            }
+        }
 
-                    var newNode = syntax.Expression
-                        .WithLeadingTrivia(leadingTrivia)
-                        .WithTrailingTrivia(trailingTrivia)
-                        .WithoutFormatting();
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, ParenthesizedExpressionSyntax syntax)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1119CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1400CodeFixProvider.cs [hunk 5]
```diff
@@ -115,14 +115,17 @@ public override FixAllProvider GetFixAllProvider()
...
-                    var syntaxRoot = await context.Document.GetSyntaxRootAsync(context.CancellationToken);
-                    var newSyntaxRoot = syntaxRoot.ReplaceNode(declarationNode, updatedDeclarationNode);
-                    var newDocument = context.Document.WithSyntaxRoot(newSyntaxRoot);
-                    context.RegisterCodeFix(CodeAction.Create("Declare accessibility", token => Task.FromResult(newDocument)), diagnostic);
+                    context.RegisterCodeFix(CodeAction.Create("Declare accessibility", token => GetTransformedDocument(context, root, declarationNode, updatedDeclarationNode)), diagnostic);
                 }
             }
         }
 
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxNode declarationNode, SyntaxNode updatedDeclarationNode)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1400CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1407SA1408CodeFixProvider.cs [hunk 6]
```diff
@@ -35,31 +35,33 @@ public override FixAllProvider GetFixAllProvider()
...
-                        .WithoutFormatting();
-
-                    var syntaxRoot = await context.Document.GetSyntaxRootAsync(context.CancellationToken);
+                    context.RegisterCodeFix(CodeAction.Create("Add parenthesis", token => GetTransformedDocument(context, root, syntax)), diagnostic);
+                }
+            }
+        }
 
-                    var newSyntaxRoot = syntaxRoot.ReplaceNode(node, newNode);
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, BinaryExpressionSyntax syntax)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1407SA1408CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1410SA1411CodeFixProvider.cs [hunk 7]
```diff
@@ -52,15 +53,17 @@ public override FixAllProvider GetFixAllProvider()
...
 
-                    var changedDocument = context.Document.WithSyntaxRoot(newSyntaxRoot);
-
-                    context.RegisterCodeFix(CodeAction.Create("Remove parenthesis", token => Task.FromResult(changedDocument)), diagnostic);
+                    context.RegisterCodeFix(CodeAction.Create("Remove parenthesis", token => GetTransformedDocument(context, root, node)), diagnostic);
                 }
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxNode node)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1410SA1411CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1100CodeFixProvider.cs [hunk 8]
```diff
@@ -35,27 +35,31 @@ public override FixAllProvider GetFixAllProvider()
...
 
-                var thisExpressionSyntax = SyntaxFactory.ThisExpression()
-                    .WithTriviaFrom(node)
-                    .WithoutFormatting();
+                context.RegisterCodeFix(CodeAction.Create("Replace 'base.' with 'this.'", token => GetTransformedDocument(context, root, node)), diagnostic);
+            }
+        }
 
-                var newSyntaxRoot = root.ReplaceNode(node, thisExpressionSyntax);
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxNode node)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1100CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1101CodeFixProvider.cs [hunk 9]
```diff
@@ -36,26 +36,31 @@ public override FixAllProvider GetFixAllProvider()
...
-                var qualifiedExpression =
-                    SyntaxFactory.MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, SyntaxFactory.ThisExpression(), node.WithoutTrivia().WithoutFormatting())
-                    .WithTriviaFrom(node)
-                    .WithoutFormatting();
+                context.RegisterCodeFix(CodeAction.Create("Prefix reference with 'this.'", token => GetTransformedDocument(context, root, diagnostic, node)), diagnostic);
+            }
+        }
 
-                var newSyntaxRoot = root.ReplaceNode(node, qualifiedExpression);
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, Diagnostic diagnostic, SimpleNameSyntax node)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1101CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1121CodeFixProvider.cs [hunk 10]
```diff
@@ -54,30 +54,39 @@ public override FixAllProvider GetFixAllProvider()
...
-                    var newRoot = root.ReplaceNode(node, newNode);
-
-                    context.RegisterCodeFix(CodeAction.Create("Replace with built-in type", token => Task.FromResult(context.Document.WithSyntaxRoot(newRoot))), diagnostic);
+                    SpecialType specialType = typeInfo.Type.SpecialType;
+                    context.RegisterCodeFix(CodeAction.Create("Replace with built-in type", token => GetTransformedDocument(context, root, node, specialType)), diagnostic);
                 }
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxNode node, SpecialType specialType)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1121CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1122CodeFixProvider.cs [hunk 11]
```diff
@@ -36,24 +46,23 @@ public override FixAllProvider GetFixAllProvider()
...
-
-                    var newSyntaxRoot = syntaxRoot.ReplaceNode(node, newNode);
-
-                    context.RegisterCodeFix(CodeAction.Create($"Replace with {newNode}", token => Task.FromResult(context.Document.WithSyntaxRoot(newSyntaxRoot))), diagnostic);
+                    context.RegisterCodeFix(CodeAction.Create($"Replace with string.Empty", token => GetTransformedDocument(context, root, node)), diagnostic);
                 }
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxNode node)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1122CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1000CodeFixProvider.cs [hunk 12]
```diff
@@ -88,25 +89,27 @@ public override FixAllProvider GetFixAllProvider()
...
-                    if (!token.HasTrailingTrivia)
-                        continue;
+            }
+        }
 
-                    SyntaxToken corrected = token.WithoutTrailingWhitespace().WithoutFormatting();
-                    Document updatedDocument = context.Document.WithSyntaxRoot(root.ReplaceToken(token, corrected));
-                    context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => Task.FromResult(updatedDocument)), diagnostic);
-                }
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxToken token, bool isAddingSpace)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1000CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1001CodeFixProvider.cs [hunk 13]
```diff
@@ -36,62 +36,66 @@ public override FixAllProvider GetFixAllProvider()
...
-                else
-                {
-                    SyntaxToken nextToken = token.GetNextToken();
-                    if (nextToken.IsKind(SyntaxKind.CommaToken) || nextToken.IsKind(SyntaxKind.GreaterThanToken))
-                    {
-                        // make an exception for things like typeof(Func<,>) and typeof(Func<,,>)
-                        missingFollowingSpace = false;
-                    }
-                }
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxToken token)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1001CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1002CodeFixProvider.cs [hunk 14]
```diff
@@ -35,53 +35,60 @@ public override FixAllProvider GetFixAllProvider()
...
-                // check for a following space
-                bool missingFollowingSpace = true;
-                if (token.HasTrailingTrivia)
-                {
-                    if (token.TrailingTrivia.First().IsKind(SyntaxKind.WhitespaceTrivia))
-                        missingFollowingSpace = false;
-                    else if (token.TrailingTrivia.First().IsKind(SyntaxKind.EndOfLineTrivia))
-                        missingFollowingSpace = false;
-                }
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxToken token)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1002CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1003CodeFixProvider.cs [hunk 15]
```diff
@@ -98,10 +99,16 @@ public override FixAllProvider GetFixAllProvider()
...
                     continue;
 
-                var transformed = root.ReplaceTokens(replacements.Keys, (original, maybeRewritten) => replacements[original]);
-                Document updatedDocument = context.Document.WithSyntaxRoot(transformed);
-                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, replacements)), diagnostic);
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, Dictionary<SyntaxToken, SyntaxToken> replacements)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1003CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1005CodeFixProvider.cs [hunk 16]
```diff
@@ -49,11 +50,17 @@ public override FixAllProvider GetFixAllProvider()
...
 
-                string correctedText = "// " + text.Substring(2);
-                SyntaxTrivia corrected = SyntaxFactory.Comment(correctedText).WithoutFormatting();
-                Document updatedDocument = context.Document.WithSyntaxRoot(root.ReplaceTrivia(trivia, corrected));
-                context.RegisterCodeFix(CodeAction.Create("Insert space", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Insert space", t => GetTransformedDocument(context, root, trivia, text)), diagnostic);
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxTrivia trivia, string text)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1005CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1006CodeFixProvider.cs [hunk 17]
```diff
@@ -48,10 +49,15 @@ public override FixAllProvider GetFixAllProvider()
...
                     continue;
 
-                SyntaxToken corrected = hashToken.WithoutTrailingWhitespace().WithoutFormatting();
-                Document updatedDocument = context.Document.WithSyntaxRoot(root.ReplaceToken(hashToken, corrected));
-                context.RegisterCodeFix(CodeAction.Create("Remove space", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Remove space", t => GetTransformedDocument(context, root, hashToken)), diagnostic);
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxToken hashToken)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1006CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1007CodeFixProvider.cs [hunk 18]
```diff
@@ -46,11 +47,17 @@ public override FixAllProvider GetFixAllProvider()
...
 
-                SyntaxTrivia whitespace = SyntaxFactory.Whitespace(" ");
-                SyntaxToken corrected = token.WithTrailingTrivia(token.TrailingTrivia.Insert(0, whitespace)).WithoutFormatting();
-                Document updatedDocument = context.Document.WithSyntaxRoot(root.ReplaceToken(token, corrected));
-                context.RegisterCodeFix(CodeAction.Create("Insert space", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Insert space", t => GetTransformedDocument(context, root, token)), diagnostic);
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxToken token)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1007CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1010CodeFixProvider.cs [hunk 19]
```diff
@@ -67,10 +67,15 @@ public override FixAllProvider GetFixAllProvider()
                 if (replacements.Count == 0)
                     continue;
 
-                var transformed = root.ReplaceTokens(replacements.Keys, (original, maybeRewritten) => replacements[original]);
-                Document updatedDocument = context.Document.WithSyntaxRoot(transformed);
-                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, replacements)), diagnostic);
             }
         }
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, Dictionary<SyntaxToken, SyntaxToken> replacements)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1010CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1011CodeFixProvider.cs [hunk 20]
```diff
@@ -98,10 +98,16 @@ public override FixAllProvider GetFixAllProvider()
...
                     continue;
 
-                var transformed = root.ReplaceTokens(replacements.Keys, (original, maybeRewritten) => replacements[original]);
-                Document updatedDocument = context.Document.WithSyntaxRoot(transformed);
-                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, replacements)), diagnostic);
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, Dictionary<SyntaxToken, SyntaxToken> replacements)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1011CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1016CodeFixProvider.cs [hunk 21]
```diff
@@ -50,11 +51,17 @@ public override FixAllProvider GetFixAllProvider()
...
 
-                SyntaxToken corrected = token.WithoutTrailingWhitespace().WithoutFormatting();
-                SyntaxNode transformed = root.ReplaceToken(token, corrected);
-                Document updatedDocument = context.Document.WithSyntaxRoot(transformed);
-                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, token)), diagnostic);
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxToken token)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1016CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1017CodeFixProvider.cs [hunk 22]
```diff
@@ -52,11 +53,17 @@ public override FixAllProvider GetFixAllProvider()
...
 
-                SyntaxToken corrected = precedingToken.WithoutTrailingWhitespace().WithoutFormatting();
-                SyntaxNode transformed = root.ReplaceToken(precedingToken, corrected);
-                Document updatedDocument = context.Document.WithSyntaxRoot(transformed);
-                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, precedingToken)), diagnostic);
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxToken precedingToken)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1017CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1018CodeFixProvider.cs [hunk 23]
```diff
@@ -52,10 +53,16 @@ public override FixAllProvider GetFixAllProvider()
...
                     continue;
 
-                SyntaxToken corrected = previousToken.WithoutTrailingWhitespace().WithoutFormatting();
-                Document updatedDocument = context.Document.WithSyntaxRoot(root.ReplaceToken(previousToken, corrected));
-                context.RegisterCodeFix(CodeAction.Create("Remove space", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Remove space", t => GetTransformedDocument(context, root, previousToken)), diagnostic);
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxToken previousToken)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1018CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1021CodeFixProvider.cs [hunk 24]
```diff
@@ -36,60 +36,67 @@ public override FixAllProvider GetFixAllProvider()
...
 
-                bool precededBySpace;
-                bool firstInLine;
-                bool followsSpecialCharacter;
+                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, token)), diagnostic);
+            }
+        }
 
-                Dictionary<SyntaxToken, SyntaxToken> replacements = new Dictionary<SyntaxToken, SyntaxToken>();
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxToken token)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1021CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1022CodeFixProvider.cs [hunk 25]
```diff
@@ -36,60 +36,68 @@ public override FixAllProvider GetFixAllProvider()
...
                     continue;
 
-                bool precededBySpace;
-                bool firstInLine;
-                bool followsSpecialCharacter;
+                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, token)), diagnostic);
+            }
+        }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxToken token)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1022CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1026CodeFixProvider.cs [hunk 26]
```diff
@@ -33,20 +33,27 @@ public override FixAllProvider GetFixAllProvider()
...
                     continue;
 
-                SyntaxToken corrected = token.WithoutTrailingWhitespace().WithoutFormatting();
-                Document updatedDocument = context.Document.WithSyntaxRoot(root.ReplaceToken(token, corrected));
-                context.RegisterCodeFix(CodeAction.Create("Remove space", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Remove space", t => GetTransformedDocument(context, root, token)), diagnostic);
             }
         }
+
+        private static Task<Document> GetTransformedDocument(CodeFixContext context, SyntaxNode root, SyntaxToken token)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1026CodeFixProvider.cs]: :exclamation: Avoid passing the `CodeFixContext` instance to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1121CodeFixProvider.cs [hunk 27]
```diff
@@ -54,30 +54,39 @@ public override FixAllProvider GetFixAllProvider()
         /// <inheritdoc/>
         public override async Task RegisterCodeFixesAsync(CodeFixContext context)
         {
+            var root = await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(false);
+            var semanticModel = await context.Document.GetSemanticModelAsync();
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1121CodeFixProvider.cs]: :exclamation: Avoid using the semantic model here; move it to the callback.

File: StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1400CodeFixProvider.cs [hunk 28]
```diff
@@ -115,14 +115,17 @@ public override FixAllProvider GetFixAllProvider()
 
                 if (updatedDeclarationNode != null)
                 {
-                    var syntaxRoot = await context.Document.GetSyntaxRootAsync(context.CancellationToken);
-                    var newSyntaxRoot = syntaxRoot.ReplaceNode(declarationNode, updatedDeclarationNode);
-                    var newDocument = context.Document.WithSyntaxRoot(newSyntaxRoot);
-                    context.RegisterCodeFix(CodeAction.Create("Declare accessibility", token => Task.FromResult(newDocument)), diagnostic);
+                    context.RegisterCodeFix(CodeAction.Create("Declare accessibility", token => GetTransformedDocument(context, root, declarationNode, updatedDeclarationNode)), diagnostic);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1400CodeFixProvider.cs]: :exclamation: Move as much of the logic from this loop to the callback as possible. Most of the work is still being done in the main loop.

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1122CodeFixProvider.cs [hunk 29]
```diff
@@ -36,24 +46,23 @@ public override FixAllProvider GetFixAllProvider()
...
                 {
-                    var identifierNameSyntax = SyntaxFactory.IdentifierName(nameof(String.Empty));
-                    var stringKeyword = SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.StringKeyword));
-                    var newNode = SyntaxFactory.MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, stringKeyword, identifierNameSyntax)
-                        .WithoutFormatting();
-
-                    var newSyntaxRoot = syntaxRoot.ReplaceNode(node, newNode);
-
-                    context.RegisterCodeFix(CodeAction.Create($"Replace with {newNode}", token => Task.FromResult(context.Document.WithSyntaxRoot(newSyntaxRoot))), diagnostic);
+                    context.RegisterCodeFix(CodeAction.Create($"Replace with string.Empty", token => GetTransformedDocument(context, root, node)), diagnostic);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1122CodeFixProvider.cs]: :question: Why not keep `{StringEmptyExpression}` in the interpolated string?

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1000CodeFixProvider.cs [hunk 30]
```diff
@@ -88,25 +89,27 @@ public override FixAllProvider GetFixAllProvider()
...
+                if (isAddingSpace == !token.HasTrailingTrivia)
                 {
-                    if (token.HasTrailingTrivia)
-                        continue;
-
-                    SyntaxTrivia whitespace = SyntaxFactory.Whitespace(" ").WithoutFormatting();
-                    SyntaxToken corrected = token.WithTrailingTrivia(token.TrailingTrivia.Insert(0, whitespace));
-                    Document updatedDocument = context.Document.WithSyntaxRoot(root.ReplaceToken(token, corrected));
-                    context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => Task.FromResult(updatedDocument)), diagnostic);
+                    context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, token, isAddingSpace)), diagnostic);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1000CodeFixProvider.cs]: :exclamation: Move as much of the logic from this loop to the callback as possible. Most of the work is still being done in the main loop.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1003CodeFixProvider.cs [hunk 31]
```diff
@@ -98,10 +99,16 @@ public override FixAllProvider GetFixAllProvider()
                 if (replacements.Count == 0)
                     continue;
 
-                var transformed = root.ReplaceTokens(replacements.Keys, (original, maybeRewritten) => replacements[original]);
-                Document updatedDocument = context.Document.WithSyntaxRoot(transformed);
-                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, replacements)), diagnostic);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1003CodeFixProvider.cs]: :exclamation: Move as much of the logic from this loop to the callback as possible.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1005CodeFixProvider.cs [hunk 32]
```diff
@@ -49,11 +50,17 @@ public override FixAllProvider GetFixAllProvider()
                 if (!text.StartsWith("//"))
                     continue;
 
-                string correctedText = "// " + text.Substring(2);
-                SyntaxTrivia corrected = SyntaxFactory.Comment(correctedText).WithoutFormatting();
-                Document updatedDocument = context.Document.WithSyntaxRoot(root.ReplaceTrivia(trivia, corrected));
-                context.RegisterCodeFix(CodeAction.Create("Insert space", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Insert space", t => GetTransformedDocument(context, root, trivia, text)), diagnostic);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1005CodeFixProvider.cs]: :exclamation: Move as much of the logic from this loop to the callback as possible (in particular, the call to `ToFullString` above).

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1006CodeFixProvider.cs [hunk 33]
```diff
@@ -48,10 +49,15 @@ public override FixAllProvider GetFixAllProvider()
                 if (!hashToken.IsKind(SyntaxKind.HashToken))
                     continue;
 
-                SyntaxToken corrected = hashToken.WithoutTrailingWhitespace().WithoutFormatting();
-                Document updatedDocument = context.Document.WithSyntaxRoot(root.ReplaceToken(hashToken, corrected));
-                context.RegisterCodeFix(CodeAction.Create("Remove space", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Remove space", t => GetTransformedDocument(context, root, hashToken)), diagnostic);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1006CodeFixProvider.cs]: :grey_exclamation: Move as much of the logic from this loop to the callback as possible.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1010CodeFixProvider.cs [hunk 34]
```diff
@@ -67,10 +67,15 @@ public override FixAllProvider GetFixAllProvider()
                 if (replacements.Count == 0)
                     continue;
 
-                var transformed = root.ReplaceTokens(replacements.Keys, (original, maybeRewritten) => replacements[original]);
-                Document updatedDocument = context.Document.WithSyntaxRoot(transformed);
-                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, replacements)), diagnostic);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1010CodeFixProvider.cs]: :exclamation: Move as much of the logic from this loop to the callback as possible.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1011CodeFixProvider.cs [hunk 35]
```diff
@@ -98,10 +98,16 @@ public override FixAllProvider GetFixAllProvider()
                 if (replacements.Count == 0)
                     continue;
 
-                var transformed = root.ReplaceTokens(replacements.Keys, (original, maybeRewritten) => replacements[original]);
-                Document updatedDocument = context.Document.WithSyntaxRoot(transformed);
-                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, replacements)), diagnostic);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1011CodeFixProvider.cs]: :exclamation: Move as much of the logic from this loop to the callback as possible.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1017CodeFixProvider.cs [hunk 36]
```diff
@@ -52,11 +53,17 @@ public override FixAllProvider GetFixAllProvider()
                 if (!precedingToken.TrailingTrivia.Any(SyntaxKind.WhitespaceTrivia))
                     continue;
 
-                SyntaxToken corrected = precedingToken.WithoutTrailingWhitespace().WithoutFormatting();
-                SyntaxNode transformed = root.ReplaceToken(precedingToken, corrected);
-                Document updatedDocument = context.Document.WithSyntaxRoot(transformed);
-                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Fix spacing", t => GetTransformedDocument(context, root, precedingToken)), diagnostic);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1017CodeFixProvider.cs]: :exclamation: Move as much of the logic from this loop to the callback as possible.

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1018CodeFixProvider.cs [hunk 37]
```diff
@@ -52,10 +53,16 @@ public override FixAllProvider GetFixAllProvider()
                 if (!previousToken.HasTrailingTrivia)
                     continue;
 
-                SyntaxToken corrected = previousToken.WithoutTrailingWhitespace().WithoutFormatting();
-                Document updatedDocument = context.Document.WithSyntaxRoot(root.ReplaceToken(previousToken, corrected));
-                context.RegisterCodeFix(CodeAction.Create("Remove space", t => Task.FromResult(updatedDocument)), diagnostic);
+                context.RegisterCodeFix(CodeAction.Create("Remove space", t => GetTransformedDocument(context, root, previousToken)), diagnostic);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1018CodeFixProvider.cs]: :exclamation: Move as much of the logic from this loop to the callback as possible.

**Comment by sharwell** [comment]
:bulb: My final comment at this point is SA1307, SA1010, and SA1011 include a call to `GetSyntaxRootAsync` which was not lifted out of the loop.

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1121CodeFixProvider.cs (hunk 27 above)
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1121CodeFixProvider.cs]: The semantic model is used in line 70(old)/74(new) to check if a CF should be provided or not. So I couldn't move it there.

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1122CodeFixProvider.cs (hunk 29 above)
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1122CodeFixProvider.cs]: Maybe its premature optimization, but this string is constant so no new string are allocated here.

**Comment by pdelvo** [comment]
To your final comment: there is no SA1307 code fix. Did you mean a different one?

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1000CodeFixProvider.cs (hunk 30 above)
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1000CodeFixProvider.cs]: I dont see an easy way to do that. I need the result of the switch statement to determine if a CF should be reported or not. Is there an easy way to do that without it?

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1003CodeFixProvider.cs (hunk 31 above)
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1003CodeFixProvider.cs]: Can I asume that replacements has items in it?

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1005CodeFixProvider.cs (hunk 32 above)
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1005CodeFixProvider.cs]: Is it possible that a signe line comment trivia does not begin with '//'?

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1006CodeFixProvider.cs (hunk 33 above)
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1006CodeFixProvider.cs]: There isnt really much being done in the main loop here. Are those if's unnessecary?

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1010CodeFixProvider.cs (hunk 34 above)
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1010CodeFixProvider.cs]: Can I asume that replacements has items in it?

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1011CodeFixProvider.cs (hunk 35 above)
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1011CodeFixProvider.cs]: Can I asume that replacements has items in it?

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1017CodeFixProvider.cs (hunk 36 above)
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1017CodeFixProvider.cs]: Are those if's unnessesary?

**Comment by sharwell** [comment]
You can always provide the code fix. If you find that no operation can be performed (i.e. the cases where the previous implementation did not provide the code fix), simply return the input document unaltered as the result of the operation.

**Comment by pdelvo** [comment]
Im actually pretty sure that this change improved performance a lot. I coud fix SA1101 on roslyns RoslynLight.sln (about 45k occurences) in one step. I tried this earler and VS would crash with a OutOfMemoryException. I havent tried with the version before, but this is the only change that happened to SA1101's code fix so thats great!

**Comment by sharwell** [comment]
That would be a very appropriate pull request, but only if you sent it today. :laughing:
