### PR TITLE
Implement a custom fix all provider for SA1133

### LINKED ISSUE #1879: SA1133 batch code fix does half the work
Given the following code (Using the `JetBrains.Annotations` NuGet package):

```csharp
using JetBrains.Annotations;

namespace Stylecop_rc1_bug_repro
{
    class Foo
    {
        [CanBeNull, UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo1{ get; set; }

        [CanBeNull, UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo2{ get; set; }

        [CanBeNull, UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo3 { get; set; }

        [CanBeNull, UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo4{ get; set; }

        [CanBeNull, UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo5{ get; set; }

        [CanBeNull, UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo6{ get; set; }

        [CanBeNull, UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo7{ get; set; }

        [CanBeNull, UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo8{ get; set; }

    }
}
```

Applying SA1133 code fix on document scope give :

```csharp
using JetBrains.Annotations;

namespace Stylecop_rc1_bug_repro
{
    class Foo
    {
        [CanBeNull]
        [UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo1 { get; set; }

        [CanBeNull, UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo2 { get; set; }

        [CanBeNull]
        [UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo3 { get; set; }

        [CanBeNull, UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo4 { get; set; }

        [CanBeNull]
        [UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo5 { get; set; }

        [CanBeNull, UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo6 { get; set; }

        [CanBeNull]
        [UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo7 { get; set; }

        [CanBeNull]
        [UsedImplicitly(ImplicitUseKindFlags.Assign)]
        public string Foo8 { get; set; }

    }
}
```

(*VS2015 update 1, StyleCop 1.0 RC1*)

### PR DESCRIPTION
**Pull request by pdelvo**
Fixes #1879.

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1133CodeFixProvider.cs [hunk 1]
```diff
@@ -80,10 +91,41 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                var nodes = diagnostics.Select(diagnostic => syntaxRoot.FindNode(diagnostic.Location.SourceSpan, getInnermostNodeForTie: true).FirstAncestorOrSelf<AttributeListSyntax>());
+
+                var newRoot = syntaxRoot.TrackNodes(nodes);
+
+                foreach (var attributeList in nodes)
+                {
+                    var indentationSteps = IndentationHelper.GetIndentationSteps(indentationOptions, attributeList);
+                    var indentationTrivia = IndentationHelper.GenerateWhitespaceTrivia(indentationOptions, indentationSteps);
+                    newRoot = newRoot.ReplaceNode(newRoot.GetCurrentNode(attributeList), GetNewAttributeList(attributeList, indentationTrivia));
+                }
```
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1133CodeFixProvider.cs]: :question: Wouldn't it be more efficient to build a dictionary of replacements and then do a single `ReplaceNodes` call?

Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1133CodeFixProvider.cs]: `ReplaceNodes` as far as I know does not support replacing one node with a set of new nodes. This is why I had to use `ReplaceNode` instead.

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1133CodeFixProvider.cs]: Yup, I forgot about that. I just had a look at the `SyntaxRewriter` as well and it also suffers from the same problem. 
It could still be done using the parent node of the `AttributeListSyntax`, but that would be a large amount of work and I'm not sure if the performance gain is significant enough for that.

**Comment by vweijsters** [comment]
:+1: Looks good to me

**Comment by sharwell** [comment]
:+1:
