### PR TITLE
Fixes SA1513 for linq query in parentheses

### LINKED ISSUE #784: SA1513 (ClosingCurlyBracketMustBeFollowedByBlankLine) should not be reported for a linq query in parentheses
A parenthesised linq query containing a multi-line anonymous object initializer raises a violation; it didn't with SC.

    // SA1513 *not* reported (correct)
    var someQuery = (from f in Enumerable.Empty<int>()
                     where f != 0
                     select new { Fish = "Face" }).ToList();

    // SA1513 reported (incorrect)
    var someOtherQuery = (from f in Enumerable.Empty<int>()
                          where f != 0
                          select new
                          {
                              Fish = "AreFriends",
                              Not = "Food"
                          }).ToList();

### PR DESCRIPTION
**Pull request by vweijsters**
Fixes #784

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/LayoutRules/SA1513ClosingCurlyBracketMustBeFollowedByBlankLine.cs [hunk 1]
```diff
@@ -183,6 +183,13 @@ private void AnalyzeCloseBrace(SyntaxToken token)
                         return;
                     }
 
+                    var parenthesizedExpressionSyntax = nextToken.Parent as ParenthesizedExpressionSyntax;
+                    if  ((parenthesizedExpressionSyntax != null) && (parenthesizedExpressionSyntax.CloseParenToken == nextToken))
```
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/LayoutRules/SA1513ClosingCurlyBracketMustBeFollowedByBlankLine.cs]: This could be simplified to 
```csharp
if  (parenthesizedExpressionSyntax?.CloseParenToken == nextToken)
```

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/LayoutRules/SA1513ClosingCurlyBracketMustBeFollowedByBlankLine.cs]: Yup, I still need to get used to having that operator available.

**Comment by vweijsters** [comment]
Update after CR
