### PR TITLE
Implement a code fix + fix all provider for SA1130

### LINKED ISSUE #1520: Code fix: SA1130 (UseLambdaSyntax)
Implement a code fix for #1451.

### PR DESCRIPTION
**Pull request by pdelvo**
Fixes #1520.

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1130CodeFixProvider.cs [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+
+        private static ParameterListSyntax RemoveType(ParameterListSyntax parameterList)
+        {
+            return parameterList.WithParameters(SyntaxFactory.SeparatedList(parameterList.Parameters.Select(x => RemoveType(x)), parameterList.Parameters.GetSeparators()));
+        }
+
+        private static ParameterSyntax RemoveType(ParameterSyntax parameterSyntax)
+        {
+            var syntax = parameterSyntax.WithType(null)
+                .WithTrailingTrivia(parameterSyntax.Type.GetLeadingTrivia().Concat(parameterSyntax.DescendantTrivia()));
```
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1130CodeFixProvider.cs]: :question: I would have expected `WithLeadingTrivia` here, why are you using `WithTrailingTrivia`?

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1130UnitTests.cs [hunk 2]
```diff
@@ -107,9 +156,141 @@ public void Test()
...
+
+            string fixedCode = @"
+using System;
+public class TypeName
+{
+    public void Test()
+    {
+        Action action1 = /*a*/()/*b*/ => { };
+        Action action2 = /*a*//*b*/(/*c*/)/*d*/ => { };
+        Action<int> action3 = /*a*//*b*//*c*/i/*d*//*e*//*f*/ => { };
```
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1130UnitTests.cs]: :thought_balloon: I think the /* d */ should be in front of the `i`.

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1130UnitTests.cs]: :thought_balloon: It might be nice to add a test case for `delegate(List</* c1 */ int> i)` for completeness.

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/Verifiers/CodeFixVerifier.cs [hunk 3]
```diff
@@ -235,11 +235,14 @@ private static Task<Document> GetFixAllAnalyzerSolutionAsync(ImmutableArray<Diag
                     break;
                 }
 
-                if (--numberOfIterations < 0)
+                if (numberOfIterations <= 0)
                 {
-                    Assert.True(false, "The upper limit for the number of fix all iterations was exceeded");
+                    // If we reached 0 we either have not fixed everything we want to fix or the code fix is not supposed to fix all violations.
+                    break;
                 }
```
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/Verifiers/CodeFixVerifier.cs]: :question: Why is this change needed? The `AreDiagnosticsDifferent` check above should be sufficient in detecting that a stable situation has been reached.

**Comment by pdelvo** [comment]
@vweijsters I implemented your feedback

**Comment by vweijsters** [comment]
:+1: Looks good to me
