### PR TITLE
Implement a code fix provider for SA1626 (SingleLineCommentsMustNotUseDocumentationStyleSlashes)

### LINKED ISSUE #655: Code fix: SA1626 (SingleLineCommentsMustNotUseDocumentationStyleSlashes)
Implement a code fix for #146.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #655

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1626CodeFixProvider.cs [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+
+        /// <inheritdoc/>
+        public override Task RegisterCodeFixesAsync(CodeFixContext context)
+        {
+            foreach (Diagnostic diagnostic in context.Diagnostics)
+            {
+                if (diagnostic.Id != SA1626SingleLineCommentsMustNotUseDocumentationStyleSlashes.DiagnosticId)
+                {
+                    continue;
+                }
```
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1626CodeFixProvider.cs]: This is different from a lot of other code fixes. Most use:
```c#
    foreach (Diagnostic diagnostic in context.Diagnostics.Where(d => FixableDiagnosticIds.Contains(d.Id)))
```

**Comment by vweijsters** [comment]
:+1: Looks good beside a minor remark

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1626CodeFixProvider.cs (hunk 1 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1626CodeFixProvider.cs]: That's because you implemented most of them. :laughing: 

I prefer this pattern because it avoids allocating an enumerator (`context.Diagnostics` is an `ImmutableArray<T>`, which has a custom struct enumerator). Note that `FixableDiagnosticIds.Contains` does not allocate because `ImmutableArray<T>` provides its own implementation of `Contains`.

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1626CodeFixProvider.cs]: You may have a point there :laughing: 
:question: Is it worth it to apply the same pattern to all code fixes? (as I mentioned, I prefer consistency :wink:)

Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1626CodeFixProvider.cs]: Actually, we should probably remove the check altogether based on dotnet/roslyn#2643 and dotnet/roslyn#2886.
