### PR TITLE
Code fix for using statements

### LINKED ISSUE #291: Code fix: SA1200 (UsingDirectivesMustBePlacedWithinNamespace)
Implement code fix for #60.

### LINKED ISSUE #292: Code fix: SA1208 (SystemUsingDirectivesMustBePlacedBeforeOtherUsingDirectives)
Implement code fix for #68.

### LINKED ISSUE #293: Code fix: SA1209 (UsingAliasDirectivesMustBePlacedAfterOtherUsingDirectives)
Implement code fix for #69.

### LINKED ISSUE #294: Code fix: SA1210 (UsingDirectivesMustBeOrderedAlphabeticallyByNamespace)
Implement code fix for #70.

### LINKED ISSUE #295: Code fix: SA1211 (UsingAliasDirectivesMustBeOrderedAlphabeticallyByAliasName)
Implement code fix for #71.

### LINKED ISSUE #1107: Code fix: SA1216 (UsingStaticDirectivesMustBePlacedAfterOtherUsingDirectives)
Implement a code fix for #653.

### LINKED ISSUE #1108: Code fix: SA1217 (UsingStaticDirectivesMustBeOrderedAlphabetically)
Implement a code fix for #652.

### PR DESCRIPTION
**Pull request by vweijsters**
- [x] Fixes #291
- [x] Fixes #292
- [x] Fixes #293 
- [x] Fixes #294 
- [x] Fixes #295 
- [x] Fixes #1107 
- [x] Fixes #1108

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 1]
```diff
@@ -0,0 +1,207 @@
...
+                    var firstPart = usingDirective.Name;
+
+                    while (firstPart is QualifiedNameSyntax)
+                    {
+                        firstPart = ((QualifiedNameSyntax)firstPart).Left;
+                    }
+
+                    var firstPartName = ((IdentifierNameSyntax)firstPart).Identifier.ValueText;
+
+                    if (string.CompareOrdinal(firstPartName, "System") == 0)
```
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: You could use `"System".Equals(firstPartName, StringComparison.Ordinal)` her instead

Comment (Przemyslaw-W) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: nameof(System)

2015-05-05 11:57 GMT+02:00 Dennis Fischer <notifications@github.com>:

Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: I didnt even know that you could use nameof with namespaces!

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: I changed the code to use `nameof(System)`

**Comment by vweijsters** [comment]
Updated to reflect the current state

**Comment by sharwell** [comment]
I'm treating this as blocked prior to implementing the rest of the `using` diagnostics (#288, #289, #290).

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 2]
```diff
@@ -0,0 +1,212 @@
...
+
+        /// <inheritdoc/>
+        public override ImmutableArray<string> FixableDiagnosticIds => FixableDiagnostics;
+
+        /// <inheritdoc/>
+        public override Task RegisterCodeFixesAsync(CodeFixContext context)
+        {
+            foreach (Diagnostic diagnostic in context.Diagnostics.Where(d => FixableDiagnostics.Contains(d.Id)))
+            {
+                context.RegisterCodeFix(CodeAction.Create("Reorder using statements", token => GetTransformedDocumentAsync(context.Document, diagnostic, token)), diagnostic);
```
Comment (Maxwe11) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: this should be updated with equivalence key

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 3]
```diff
@@ -0,0 +1,212 @@
...
+            }
+
+            return Task.FromResult(true);
```
Comment (Maxwe11) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: `SpecializedTasks.CompletedTask`

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 4]
```diff
@@ -0,0 +1,212 @@
...
+                    {
+                        otherUsings.Add(usingDirective);
+                    }
+                }
+            }
+
+            systemUsings.Sort(CompareName);
+            otherUsings.Sort(CompareName);
+            aliases.Sort(CompareAliasName);
+            staticImports.Sort(CompareName);
```
Comment (Maxwe11) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: Delegate for `CompareName` will be allocated 3 times. I'd replaced it with a lambda.

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 5]
```diff
@@ -0,0 +1,212 @@
...
+            var rootNamespace = newSyntaxRoot.ChildNodes().OfType<NamespaceDeclarationSyntax>().FirstOrDefault();
+
+            var indentationLevel = IndentationHelper.GetIndentationSteps(indentationOptions, rootNamespace);
+            var usingsIndentation = IndentationHelper.GenerateIndentationString(indentationOptions, indentationLevel + 1);
+
+            var syntaxList = SyntaxFactory.List<UsingDirectiveSyntax>();
+            syntaxList = AppendUsings(syntaxList, systemUsings, usingsIndentation);
+            syntaxList = AppendUsings(syntaxList, otherUsings, usingsIndentation);
+            syntaxList = AppendUsings(syntaxList, aliases, usingsIndentation);
+            syntaxList = AppendUsings(syntaxList, staticImports, usingsIndentation);
```
Comment (Maxwe11) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: Could we create one `List<UsingDirectiveSyntax>` with all using in correct order and then create `SyntaxList<UsingDirectiveSyntax>` from it?These mutations looks weird and not effective.

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 6]
```diff
@@ -0,0 +1,212 @@
...
+        private static SyntaxList<UsingDirectiveSyntax> AppendUsings(SyntaxList<UsingDirectiveSyntax> syntaxList, List<UsingDirectiveSyntax> usings, string indentation)
+        {
+            if (usings.Count > 0)
+            {
+                var processedUsings = new List<UsingDirectiveSyntax>();
+
+                for (var i = 0; i < usings.Count; i++)
+                {
+                    var currentUsing = usings[i];
+                    var processedUsing = currentUsing.WithLeadingTrivia(SyntaxFactory.Whitespace(indentation)).WithTrailingTrivia(SyntaxFactory.CarriageReturnLineFeed);
```
Comment (Maxwe11) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: >SyntaxFactory.CarriageReturnLineFeed
:question: 
What if original code contains only line feeds? :smile:

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs (hunk 4 above)
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: I would be amazed if one of the optimizers would not catch that and reduce it to a single allocation.

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs (hunk 6 above)
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: Then there would be inconsistency. There's lots of places where the same would happen, either with LF vs CRLF or space vs Tab. I'll create an issue to fix this somewhere in the future for the entire codebase.

**Comment by Noryoko** [comment]
:question: Can you update the unit tests for the diagnostics from `DiagnosticVerifier` to `CodeFixVerifier`?

:question: In the case of directive trivia surrounding using statements outside of a namespace how will these be handled?

Moving the using statement into the namespace in the following example will cause a compiler error. This is handled correctly by the diagnostic. Pointing it out as a heads up.
```
using System.Reflection;

[assembly: AssemblyVersion("1.0.0.0")]

namespace TestNamespace { }
```

**Comment by sharwell** [comment]
@vweijsters I'd love to include this, but first I want to make sure it accounts for a couple of things to make sure we don't break users' code.

1. When SA1200 is suppressed, the code fix should not attempt to move the `using` declarations inside a namespace.

2. When the file contains items declared outside a namespace (such as @Noryoko's example), or when the file contains more than one namespace, the code fix should not attempt to move `using` declarations inside a namespace.

3. The code fix should account for #1161 when reordering directives. In addition, the code fix should not attempt to move using directives inside a namespace if the group contained unbalanced preprocessor directives.

**Comment by vweijsters** [comment]
I've been busy the last couple of days. This one is first on my list for the coming week

**Comment by sharwell** [comment]
Thanks for the update. :smile: I marked it as **in progress** with a tentative milestone of Beta 10.

**Comment by vweijsters** [comment]
Updated with all remarks above. Also rebased/squashed.

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/OrderingRules/SA1209UnitTests.cs [hunk 7]
```diff
@@ -58,6 +60,31 @@ class A
...
+    using P = System.Threading.Tasks;
+
+    class A
+    {
+    }
+}";
+
             DiagnosticResult[] expectedForCompilationUnit =
             {
                 this.CSharpDiagnostic().WithLocation(1, 1)
```
Comment (Noryoko) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/OrderingRules/SA1209UnitTests.cs]: :bulb: Single diagnostics can be:
`var expected = this.CSharpDiagnostic().WithLocation(1, 1);`

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 8]
```diff
@@ -0,0 +1,642 @@
...
+                    continue;
+                }
+
+                context.RegisterCodeFix(CodeAction.Create(OrderingResources.UsingCodeFix, token => GetTransformedDocumentAsync(context.Document, diagnostic, token), equivalenceKey: nameof(UsingCodeFixProvider)), diagnostic);
+            }
+        }
+
+        private static async Task<Document> GetTransformedDocumentAsync(Document document, Diagnostic diagnostic, CancellationToken cancellationToken)
+        {
+            var syntaxRoot = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
```
Comment (Noryoko) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: :question: Could `syntaxRoot` be passed in?

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/OrderingRules/SA1209UnitTests.cs [hunk 9]
```diff
@@ -88,12 +118,28 @@ class A
     }
 }";
 
+            var fixedTestCode = @"namespace Test
+{
+    using global::System;
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/OrderingRules/SA1209UnitTests.cs]: :exclamation: A namespace prefixed with `global::` should not ever be considered a `System` using directive.

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 10]
```diff
@@ -0,0 +1,642 @@
...
+
+            // Only move usings inside the namespace when
+            // - SA1200 is enabled
+            // - There are no global attributes
+            // - There is only a single namespace declared at the top level
+            var moveInsideNamespace =
+                !document.IsAnalyzerSuppressed(SA1200UsingDirectivesMustBePlacedWithinNamespace.DiagnosticId)
+                && !compilationUnit.AttributeLists.Any()
+                && compilationUnit.Members.Count == 1
+                && namespaceCount == 1;
```
Comment (Noryoko) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: :question: Possible performance gain checking `namespaceCount` first.

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/OrderingRules/SA1209UnitTests.cs [hunk 11]
```diff
@@ -153,12 +213,28 @@ class A
     }
 }";
 
+            var fixedTestCode = @"namespace Test
+{
+    using System;
+    using System.Net;
+
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/OrderingRules/SA1209UnitTests.cs]: :bulb: I would prefer the blank lines between groups be removed.

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 12]
```diff
@@ -0,0 +1,642 @@
...
+            BuildReplaceMapForConditionalDirectives(usingsHelper, replaceMap, indentationOptions, usingsHelper.RootSpan);
+
+            var usingSyntaxRewriter = new UsingSyntaxRewriter(stripList, replaceMap);
+            var newSyntaxRoot = usingSyntaxRewriter.Visit(syntaxRoot);
+
+            if (moveInsideNamespace)
+            {
+                newSyntaxRoot = AddUsingsToNamespace(newSyntaxRoot, usingsHelper, usingsIndentation, replaceMap.Any());
+            }
+            else if (namespaceCount <= 1)
```
Comment (Noryoko) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: :bulb: 1 is not a possible value for this case. A `true` value for `moveInsideNamespace` requires `namespaceCount` be 1.

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 13]
```diff
@@ -0,0 +1,642 @@
...
+            var newDocument = document.WithSyntaxRoot(newSyntaxRoot.WithoutFormatting());
+
+            return newDocument;
+        }
+
+        private static int CountNamespaces(SyntaxList<MemberDeclarationSyntax> members)
+        {
+            var result = 0;
+
+            foreach (var namespaceDeclaration in members.OfType<NamespaceDeclarationSyntax>())
```
Comment (Noryoko) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: :bulb: Using Linq will cause boxing.

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 14]
```diff
@@ -0,0 +1,642 @@
...
+        {
+            var usingsPerNamespace = usingsHelper
+                .GetContainedUsings(usingsHelper.RootSpan)
+                .GroupBy(ud => ud.Parent)
+                .Select(gr => gr.ToList());
+
+            foreach (var usingList in usingsPerNamespace)
+            {
+                if (usingList.Count > 0)
+                {
```
Comment (Noryoko) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: Could use `continue` to reduce nesting.

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs [hunk 15]
```diff
@@ -0,0 +1,642 @@
...
+        }
+
+        private static int CompareSpanStart(UsingDirectiveSyntax left, UsingDirectiveSyntax right)
+        {
+            return left.SpanStart - right.SpanStart;
+        }
+
+        private static SyntaxNode AddUsingsToNamespace(SyntaxNode newSyntaxRoot, UsingsHelper usingsHelper, string usingsIndentation, bool hasConditionalDirectives)
+        {
+            var rootNamespace = ((CompilationUnitSyntax)newSyntaxRoot).Members.OfType<NamespaceDeclarationSyntax>().First();
```
Comment (Noryoko) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: :bulb: Linq will cause boxing. Seems like a good canidate for a new method in `SyntaxTriviaListEnumerable`.

**Comment by Noryoko** [comment]
Can you add a test that includes a file header?

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs (hunk 10 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: I don't think it makes a difference.

**Comment by sharwell** [comment]
I'll send a follow-up pull request to address the final feedback.

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs (hunk 14 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: This didn't seem like a big win because it's not possible to do the same thing in the method that follows (`BuildReplaceMapForConditionalDirectives`).

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs (hunk 13 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: Highly unlikely to even be observable in this code fix provider.

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs (hunk 12 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: But this is the `false` case for `moveInsideNamespace`.

Comment (Noryoko) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/UsingCodeFixProvider.cs]: My bad on this one.
