### PR TITLE
Implemented SA1103, SA1104, SA1105 (incl. code fix + tests)

### LINKED ISSUE #37: SA1103: QueryClausesMustBeOnSeparateLinesOrAllOnOneLine
http://www.stylecop.com/docs/SA1103.html

### LINKED ISSUE #38: SA1104: QueryClauseMustBeginOnNewLineWhenPreviousClauseSpansMultipleLines
http://www.stylecop.com/docs/SA1104.html

### LINKED ISSUE #39: SA1105: QueryClausesSpanningMultipleLinesMustBeginOnOwnLine
http://www.stylecop.com/docs/SA1105.html

### LINKED ISSUE #507: Code fix: SA1102 (QueryClauseMustFollowPreviousClause)
Implement a code fix for #36.

### PR DESCRIPTION
**Pull request by vweijsters**
Fixes #37
Fixes #38
Fixes #39
Fixes #507

### CODE REVIEW

**Comment by vweijsters** [comment]
Mark this one `do not merge` for now please. I'm going to try and see if I can create a single analyzer for SA1103, SA1104, and SA1105 within this pull request.

**Comment by vweijsters** [comment]
- Combined SA1102, SA1103, SA1104, and SA1105 into a single analyzer
- Implemented code fixes for SA1102, SA1104, and SA1105
- Modified test cases to comply with all 4 diagnostics.

I'm done with this one, so the **do not merge** and **in progress** tags can go as far as I'm concerned.

File: StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DiagnosticOptionsHelper.cs [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+    using System.Collections.Immutable;
+    using Microsoft.CodeAnalysis;
+    using Microsoft.CodeAnalysis.Diagnostics;
+
+    /// <summary>
+    /// Provides helper methods to work with diagnostics options.
+    /// </summary>
+    internal static class DiagnosticOptionsHelper
+    {
+        internal static bool IsAnalyzerEnabled(this SyntaxNodeAnalysisContext context, string analyzerId)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DiagnosticOptionsHelper.cs]: :bulb: I would prefer to see this method be changed to `IsAnalyzerSuppressed`. The lack of a suppression does not mean the analyzer is enabled.

**Comment by sharwell** [comment]
:bulb: This would be a good time to migrate the documentation files from the StyleCop site to the documentation subfolder of this repository.

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA110xQueryClauses.cs [hunk 2]
```diff
@@ -0,0 +1,239 @@
...
+
+        /// <summary>
+        /// Gets the diagnostic descriptor for SA1105.
+        /// </summary>
+        /// <value>The <see cref="DiagnosticDescriptor"/> for SA1105.</value>
+        public static DiagnosticDescriptor SA1105Descriptor { get; } =
+            new DiagnosticDescriptor(SA1105Identifier, SA1105Title, SA1105MessageFormat, Category, DiagnosticSeverity.Warning, AnalyzerConstants.EnabledByDefault, SA1105Description, SA1105HelpLink);
+
+        /// <inheritdoc/>
+        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics { get; } =
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA110xQueryClauses.cs]: :thought_balloon: This is the way to go for these properties.

**Comment by vweijsters** [comment]
Updated after CR

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1102CodeFixProvider.cs [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+
+        /// <inheritdoc/>
+        public override Task RegisterCodeFixesAsync(CodeFixContext context)
+        {
+            foreach (var diagnostic in context.Diagnostics.Where(d => FixableDiagnostics.Contains(d.Id)))
+            {
+                context.RegisterCodeFix(CodeAction.Create(ReadabilityResources.SA1102CodeFix, token => GetTransformedDocumentAsync(context.Document, diagnostic, token)), diagnostic);
+            }
+
+            return Task.FromResult(true);
```
Comment (Maxwe11) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1102CodeFixProvider.cs]: ` SpecializedTasks.CompletedTask`

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1103CodeFixProvider.cs [hunk 4]
```diff
@@ -0,0 +1,154 @@
...
+                    return lineSpan.StartLinePosition.Line == lineSpan.EndLinePosition.Line;
+
+                default:
+                    return false;
+            }
+        }
+
+        private static async Task<Document> GetTransformedDocumentFromSingleLineAsync(Document document, Diagnostic diagnostic, CancellationToken cancellationToken)
+        {
+            var syntaxRoot = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
```
Comment (Maxwe11) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1103CodeFixProvider.cs]: Why not get this root `RegisterCodeFixesAsync` ?

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1102CodeFixProvider.cs (hunk 3 above)
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1102CodeFixProvider.cs]: Good catch, I'll change that.

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1103CodeFixProvider.cs (hunk 4 above)
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1103CodeFixProvider.cs]: That is a possibility, but I prefer to have the "standard" signature for GetTransformedDocumentAsync methods.

I think it will hardly make a difference performance wise, as this code is only executed whenever the user selects to perform an action. And the results of the `GetSyntaxRootAsync` method is cached as well.

**Comment by vweijsters** [comment]
Updated to use `SpecializedTasks.CompletedTask`
