### PR TITLE
Implemented SA1136 (incl. tests and code fix)

### LINKED ISSUE #1854: Implement SA1136: Enum values should be on separate lines
**Category:** Readability
**Title:** Enum values should be on separate lines

Code that will trigger it:

```cs
public enum SomeEnumType
{
    FirstValue, SecondValue, ThirdValue
}
```

Corrected code:
```cs
public enum SomeEnumType
{
    FirstValue,
    SecondValue,
    ThirdValue
}
```

### PR DESCRIPTION
**Pull request by vweijsters**
Fixes #1854

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1136CodeFixProvider.cs [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+                .Add(SyntaxFactory.CarriageReturnLineFeed);
+
+            replacements[precedingSeparatorToken] = precedingSeparatorToken.WithTrailingTrivia(newTrailingTrivia);
+            replacements[enumMemberDeclarationFirstToken] = enumMemberDeclarationFirstToken.WithLeadingTrivia(indentation);
+
+            var newSyntaxRoot = syntaxRoot.ReplaceTokens(replacements.Keys, (original, rewritten) => replacements[original]);
+            var newDocument = document.WithSyntaxRoot(newSyntaxRoot.WithoutFormatting());
+
+            return newDocument;
+        }
```
Comment (lukas-ais) [inline StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1136CodeFixProvider.cs]: I would like to see some code comments on the steps of transformation.

**Comment by vweijsters** [comment]
Rebased and added comments

File: StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1136CodeFixProvider.cs [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+
+            return SpecializedTasks.CompletedTask;
+        }
+
+        private static async Task<Document> GetTransformedDocumentAsync(Document document, Diagnostic diagnostic, CancellationToken cancellationToken)
+        {
+            var syntaxRoot = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
+            var settings = SettingsHelper.GetStyleCopSettings(document.Project.AnalyzerOptions, cancellationToken);
+
+            var enumMemberDeclaration = (EnumMemberDeclarationSyntax)syntaxRoot.FindNode(diagnostic.Location.SourceSpan, getInnermostNodeForTie: true);
```
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1136CodeFixProvider.cs]: :question: Does "getInnermostNodeForTie" matter here?

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1136EnumValuesShouldBeOnSeparateLines.cs [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+        private static void HandleCompilationStart(CompilationStartAnalysisContext context)
+        {
+            context.RegisterSyntaxNodeActionHonorExclusions(HandleEnumDeclarationAction, SyntaxKind.EnumDeclaration);
+        }
+
+        private static void HandleEnumDeclaration(SyntaxNodeAnalysisContext context)
+        {
+            var enumDeclaration = (EnumDeclarationSyntax)context.Node;
+
+            if (enumDeclaration.Members.Count < 2)
```
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1136EnumValuesShouldBeOnSeparateLines.cs]: can "Members" be null here? What happens for:

```csharp
enum Foo
```
with the block missing?

Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1136EnumValuesShouldBeOnSeparateLines.cs]: There should probably be a test for this.

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1136EnumValuesShouldBeOnSeparateLines.cs]: Members cannot be null, as it is of type `SeparatedSyntaxList<T>` which is a `struct`.
I doubt that there is much benefit in the testcase because of that, but I'll add it anyway.

File: StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1136CodeFixProvider.cs (hunk 2 above)
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/ReadabilityRules/SA1136CodeFixProvider.cs]: No, it doesn't. The enum member declaration can never have the same span as the enum declaration. I'll remove it.

**Comment by vweijsters** [comment]
Update after CR

**Comment by pdelvo** [comment]
:+1:

**Comment by vweijsters** [comment]
Rebased and updated to work with roslyn-1.2
