### PR TITLE
SA1648 throws an exception on delegates that use the <include> tag

### LINKED ISSUE #3291: SA1648 throws an exception on delegates that use the <include> tag
The diagnostic analyzer for SA1648 throws an `ArgumentNullException` when analyzing delegates that have an `<include>` tag in their XML attributes.

The following line throws the exception during the analysis:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/23db6c032f6b1ca8d3e280f7150ac7685b749881/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1648InheritDocMustBeUsedWithInheritingClass.cs#L89

The exception is thrown because the local `baseType` is `null` because it has no direct base type in the syntax tree.
See also:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/23db6c032f6b1ca8d3e280f7150ac7685b749881/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1648InheritDocMustBeUsedWithInheritingClass.cs#L73-L74

I have prepared a reproduction repository, which you can find here: https://github.com/angelobreuer/SA1648DelegateRepro

Additionally, I have prepared a pull request, which will come up in a few minutes.

### PR DESCRIPTION
**Pull request by angelobreuer**
Tracking issue: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3291

This PR includes the following changes:
- Fix #3291 
- Add two tests

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1648InheritDocMustBeUsedWithInheritingClass.cs [hunk 1]
```diff
@@ -86,7 +86,7 @@ private static void HandleBaseTypeLikeDeclaration(SyntaxNodeAnalysisContext cont
 
             if (documentation.Content.GetFirstXmlElement(XmlCommentHelper.IncludeXmlTag) is XmlEmptyElementSyntax includeElement)
             {
-                var declaration = context.SemanticModel.GetDeclaredSymbol(baseType, context.CancellationToken);
+                var declaration = baseType is null ? context.ContainingSymbol : context.SemanticModel.GetDeclaredSymbol(baseType, context.CancellationToken);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1648InheritDocMustBeUsedWithInheritingClass.cs:89]: 💭 It seems like the intent would be closer to this:

```suggestion
                var declaration = context.SemanticModel.GetDeclaredSymbol(context.Node, context.CancellationToken);
```

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs [hunk 2]
```diff
@@ -305,6 +305,53 @@ public class TestClass : ITest
             await VerifyCSharpDiagnosticAsync(testCode, expected, CancellationToken.None).ConfigureAwait(false);
         }
 
+        /// <summary>
+        /// Verifies that a delegate declaration that includes the inheritdoc will produce diagnostics.
+        /// </summary>
+        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
+        [Fact]
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs:312]:
```suggestion
        [Fact]
        [WorkItem(3291, "https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3291")]
```

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs [hunk 3]
```diff
@@ -305,6 +305,53 @@ public class TestClass : ITest
...
+
+            var expected = Diagnostic().WithLocation(10, 7);
+            await VerifyCSharpDiagnosticAsync(testCode, expected, CancellationToken.None).ConfigureAwait(false);
+        }
+
+        /// <summary>
+        /// Verifies that a delegate declaration that includes the inheritdoc will produce diagnostics.
+        /// </summary>
+        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
+        [Fact]
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs:337]:
```suggestion
        [Fact]
        [WorkItem(3291, "https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3291")]
```

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs [hunk 4]
```diff
@@ -305,6 +305,53 @@ public class TestClass : ITest
...
+            var testCode = @"
+/// <summary>Foo</summary>
+/// <param name=""value"">some param</param>
+/// <returns>something</returns>
+public delegate bool TestDelegate(int value);
+
+/// <summary>Test class</summary>
+public class TestClass
+{
+  /// <include file='DelegateInheritDoc.xml' path='/TestDelegate/*'/>
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs:324]:
```suggestion
  /// {|#0:<include file='DelegateInheritDoc.xml' path='/TestDelegate/*'/>|}
```

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs [hunk 5]
```diff
@@ -305,6 +305,53 @@ public class TestClass : ITest
...
+  public delegate bool TestDelegate(int value);
+}
+";
+
+            var expected = Diagnostic().WithLocation(10, 7);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs:329]:
```suggestion
            var expected = Diagnostic().WithLocation(0);
```

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs [hunk 6]
```diff
@@ -305,6 +305,53 @@ public class TestClass : ITest
...
+        [Fact]
+        public async Task TestIncorrectDelegateInheritDocAsync()
+        {
+            var testCode = @"
+public delegate bool TestDelegate(int value);
+
+/// <summary>Test class</summary>
+public class TestClass
+{
+  /// <include file='DelegateInheritDoc.xml' path='/TestDelegate/*'/>
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs:346]:
```suggestion
  /// {|#0:<include file='DelegateInheritDoc.xml' path='/TestDelegate/*'/>|}
```

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs [hunk 7]
```diff
@@ -305,6 +305,53 @@ public class TestClass : ITest
...
+  public delegate bool TestDelegate(int value);
+}
+";
+
+            var expected = Diagnostic().WithLocation(7, 7);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1648UnitTests.cs:351]:
```suggestion
            var expected = Diagnostic().WithLocation(0);
```

**Review by sharwell — APPROVED** [review]
Implementation looks good. I had a few suggestions to improve the tests.

**Review by sharwell — APPROVED** [review]

**Comment by sharwell** [comment]
Thanks @angelobreuer !
