### PR TITLE
Implemented SA1027 unit tests + code fix

### LINKED ISSUE #235: Diagnostic unit tests: TabsMustNotBeUsed
Implement unit tests for #33.

### LINKED ISSUE #243: Code fix: TabsMustNotBeUsed
Implement code fix for #33.

### PR DESCRIPTION
**Pull request by vweijsters**
Fixes #235
Fixed #243

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1027CodeFixProvider.cs [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+        }
+
+        private static async Task<Document> GetTransformedDocumentAsync(Document document, Diagnostic diagnostic, CancellationToken cancellationToken)
+        {
+            var indentationOptions = IndentationOptions.FromDocument(document);
+            var syntaxRoot = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
+
+            var violatingTrivia = syntaxRoot.FindTrivia(diagnostic.Location.SourceSpan.Start);
+
+            var tabReplacement = new string(' ', indentationOptions.TabSize);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1027CodeFixProvider.cs]: :exclamation: This only works if the hard tab appears at the beginning of the line, but I don't think that's the only thing this diagnostic looks for.

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1027CodeFixProvider.cs]: Good spot, I never considered that. I'll work on a fix.

**Comment by sharwell** [comment]
:bulb: Add a test for a block of text inside `#if false` (it should be ignored).

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/SpacingRules/SA1027UnitTests.cs [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+                "public class Foo\r\n" +
+                "{\r\n" +
+                "\tpublic void Bar()\r\n" +
+                "\t{\r\n" +
+                "\t  \t// Comment\r\n" +
+                "\t \tDebug.Indent();\r\n" +
+                "   \t}\r\n" +
+                "}\r\n";
+
+            // There is only a single space between the using and the System.Diagnostics,
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/SpacingRules/SA1027UnitTests.cs]: :exclamation: This is not correct. The code fix should result in 3 spaces between `using` and `System`.

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/SpacingRules/SA1027UnitTests.cs]: I don't agree. Inserting three spaces there will indeed keep the original layout, but it will immediately trigger SA1025, something that is not desirable in my opinion.

**Comment by vweijsters** [comment]
Added the `#if false` test case.

File: StyleCop.Analyzers/StyleCop.Analyzers.Test/SpacingRules/SA1027UnitTests.cs (hunk 2 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/SpacingRules/SA1027UnitTests.cs]: In general we don't make cross-rule special cases for the code fixes. The only cases where we fix multiple violations at once is renaming a variable that contains the same violation more than once (e.g. #627).

Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/SpacingRules/SA1027UnitTests.cs]: For example, what if this code is contained in the following?

```csharp
#pragma warning disable SA1025
[something with a hard tab]
#pragma warning restore SA1025
```

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers.Test/SpacingRules/SA1027UnitTests.cs]: Not making cross-rule specials will definitely keep the code more simple in the long run, which is good.
I was looking at that a bit too much from how I would use it, which may of course not be how other people see it. I'll change the code.

**Comment by vweijsters** [comment]
The code fix provider will now always add the amount of spaces required to keep the formatting the same.
