### PR TITLE
Fix that TriviaHelper.WithoutLeadingBlankLines can throw exception

### LINKED ISSUE #1285: TriviaHelper.WithoutLeadingBlankLines bug
In #1252 there's now a failing test as a result of TriviaHelper.WithoutLeadingBlankLines throwing an index out of range exception on line 299 with this code:
```CSharp
public class Foo
{
    private int i = 0;

    public int Prop
    {
        /// <summary>
        /// The setter documentation
        /// </summary>
        set
        {
            i = value;
        }

        /// <summary>
        /// The getter documentation
        /// </summary>
        get
        {
            return i;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by pdelvo**
Fixes #1285.

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/Helpers/TriviaHelper.cs [hunk 1]
```diff
@@ -311,6 +311,24 @@ internal static SyntaxToken WithoutLeadingBlankLines(this SyntaxToken token)
             return token.WithLeadingTrivia(newLeadingTrivia);
         }
 
+        private static bool HasBuiltinEndLine(this SyntaxTrivia trivia)
+        {
+            switch (trivia.Kind())
+            {
+            case SyntaxKind.SingleLineDocumentationCommentTrivia:
+            case SyntaxKind.PragmaWarningDirectiveTrivia:
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/TriviaHelper.cs]: :exclamation: *All* directive trivia (i.e. the ones where `IsDirective` is true) contain a built-in end line. Some of them were left out here.

**Comment by pdelvo** [comment]
I implemented the feedback

**Comment by sharwell** [comment]
:+1:
