### PR TITLE
Fix that SA1649 does not support simple names

### LINKED ISSUE #1730: SA1649 (File name must match first type name) for generic types shouldn't require generic specification
For the type `Fish<T>`, legacy StyleCop permits either "Fish{T}.cs" *or* "Fish.cs" as the file name.

Our analyzer allows the former, prefers "Fish`1" but does not accept plain old "Fish.cs". I like the legacy behaviour, since I prefer to omit the qualification in the file name unless there is a non-generic version of the type too.

Apologies if this has already been discussed, but I couldn't find evidence of that.

### PR DESCRIPTION
**Pull request by pdelvo**
Fixes #1730.

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1649FileNameMustMatchTypeName.cs [hunk 1]
```diff
@@ -84,22 +84,22 @@ public void HandleSyntaxTreeAction(SyntaxTreeAnalysisContext context)
                 }
 
                 var fileName = Path.GetFileName(context.Tree.FilePath);
-                string expectedFileName;
+                string[] expectedFileNames;
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1649FileNameMustMatchTypeName.cs]: :question: Since this is in an analyzer (as opposed to a code fix), can we implement this without the additional array and closure allocations?

Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1649FileNameMustMatchTypeName.cs]: I changed that

**Comment by vweijsters** [comment]
:+1: Looks good to me
