### PR TITLE
Implement custom SA1005 fix all provider

### LINKED ISSUE #1402: Write fix all provider for SA1005 (SingleLineCommentsMustBeginWithSingleSpace)
I'm seeing 3451 violations in Roslyn.sln, making this a valuable addition for performance.

### PR DESCRIPTION
**Pull request by pdelvo**
Fixes #1402

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1005CodeFixProvider.cs [hunk 1]
```diff
@@ -46,29 +48,60 @@ public override FixAllProvider GetFixAllProvider()
                     continue;
                 }
 
-                SyntaxTrivia trivia = root.FindTrivia(diagnostic.Location.SourceSpan.Start, findInsideTrivia: true);
-                if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia))
+                context.RegisterCodeFix(CodeAction.Create(SpacingResources.SA1005CodeFix, t => GetTransformedDocumentAsync(context.Document, diagnostic.Location, context.CancellationToken), equivalenceKey: nameof(SA1005CodeFixProvider)), diagnostic);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1005CodeFixProvider.cs]: :exclamation: You are passing the wrong `CancellationToken` to `GetTransformedDocumentAsync`. You need to rename `t` to `cancellationToken` and pass that instead.

Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1005CodeFixProvider.cs]: Fixed
