### PR TITLE
Variable and parameter naming analyzers and fixes

### LINKED ISSUE #1310: New rule proposal: VariableNamesMustBeginWithLowerCaseLetter
**Category:** Naming
**Title:** Variable names must begin with lower case letter
**Description:** This is very similar to SA1306, but it applies specifically to non-`const` local variables.

This functionality is handled by SA1306 in StyleCop classic, but the commentary in #1307 suggests that we continue to implement SA1306 in a more strict manner here and report variables separately. One advantage of treating local variables separately from fields is renaming them is *always* a non-breaking change (they are not even exposed via Reflection), so the ability to "fix all" on these would be valuable and trusted provided it only touched local variables.

### LINKED ISSUE #1311: New rule proposal: ParameterNamesMustBeginWithLowerCaseLetter
**Category:** Naming
**Title:** Parameter names must begin with lower case letter
**Description:** This is very similar to SA1306, but it applies specifically to parameters of methods and delegates.

This proposal was created based on feedback in #1307. This proposal is separated from #1310 due to the fact that renaming a parameter is a source-breaking change (call sites using named arguments need to be updated).

### PR DESCRIPTION
**Pull request by sharwell**
This pull request adds two new rules:

* SA1312 (VariableNamesMustBeginWithLowerCaseLetter) (fixes #1310)
* SA1313 (ParameterNamesMustBeginWithLowerCaseLetter) (fixes #1311)

It also updates the documentation for SA1306 (FieldNamesMustBeginWithLowerCaseLetter) to explicitly state the deviation from StyleCop "classic".

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/NamingRules/SA1312VariableNamesMustBeginWithLowerCaseLetter.cs [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+            LocalDeclarationStatementSyntax parentDeclaration = syntax.Parent as LocalDeclarationStatementSyntax;
+            if (parentDeclaration?.IsConst ?? false)
+            {
+                // this diagnostic does not apply to locals constants
+                return;
+            }
+
+            foreach (VariableDeclaratorSyntax variableDeclarator in syntax.Variables)
+            {
+                if (variableDeclarator == null)
```
Comment (Noryoko) [inline StyleCop.Analyzers/StyleCop.Analyzers/NamingRules/SA1312VariableNamesMustBeginWithLowerCaseLetter.cs]: :question: Is `null` possible?

**Comment by Noryoko** [comment]
Other than the question. Looks good. :+1:

File: StyleCop.Analyzers/StyleCop.Analyzers/NamingRules/SA1312VariableNamesMustBeginWithLowerCaseLetter.cs (hunk 1 above)
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/NamingRules/SA1312VariableNamesMustBeginWithLowerCaseLetter.cs]: I have no idea.
