### PR TITLE
Made SA1130 codefix properly expand parameters when only delegate key…

### LINKED ISSUE #2593: SA1130 Code Fix Generates Incorrect Code
# Description
The line below, tagged "this line", flags SA1130:
## Sample 1: Violation
```csharp
using System;

namespace StyleCopDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            // this line:
            EventHandler anon = delegate { Console.WriteLine("hello"); };
        }
    }
}
```

The fix, however, transforms it into something that's syntactically incorrect:
## Sample 2: Incorrect Fix
```csharp
using System;

namespace StyleCopDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            // this line:
            EventHandler anon = () => { Console.WriteLine("hello"); };
        }
    }
}
```

If there's going to be a code fix for this, then a legal fix would be:
## Sample 3: Legal Fix
```csharp
using System;

namespace StyleCopDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            // this line:
            EventHandler anon = (sender, args1) => { Console.WriteLine("hello"); };
        }
    }
}
```

# Environment
Visual Studio Enterprise 15.5.3
StyleCop.Analyzers: version 1.1.0-beta004 from NuGet

.NET Core 2.0, with the following .csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta004" />
  </ItemGroup>
</Project>
```

### PR DESCRIPTION
**Pull request by vweijsters**
…word is used

Fixes #2593

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1130UseLambdaSyntax.cs [hunk 1]
```diff
@@ -47,35 +54,130 @@ public override void Initialize(AnalysisContext context)
...
+            foreach (var symbolParameter in symbolParameters)
+            {
+                var syntaxParameter = GetParameterSyntaxFromParameterSymbol(symbolParameter);
+                result.Add(syntaxParameter);
+            }
+
+            return result.ToImmutable();
+        }
+
+        private static ParameterSyntax GetParameterSyntaxFromParameterSymbol(IParameterSymbol symbolParameter)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1130UseLambdaSyntax.cs]: ❓ Is it possible to move this logic into the code fix instead? Moving it would improve the performance of the main analyzer by not requiring as much symbol analysis, and then the code fix is a bit slower but at that point users have explicitly requested the system take action.

If the new analysis logic affects when/where diagnostics are reported (and thus can't be moved), can you call those cases out?

Comment (vweijsters) [reply StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1130UseLambdaSyntax.cs]: I'll have a look

Comment (vweijsters) [reply StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1130UseLambdaSyntax.cs]: @sharwell I've moved the code necessary to determine the correct parameter list to the code fix. Can you have a look again?

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1130UseLambdaSyntax.cs [hunk 2]
```diff
@@ -45,37 +47,104 @@ public override void Initialize(AnalysisContext context)
...
+                break;
+            }
+
+            if (reportDiagnostic)
+            {
+                context.ReportDiagnostic(Diagnostic.Create(Descriptor, anonymousMethod.DelegateKeyword.GetLocation(), diagnosticProperties.ToImmutable()));
+            }
+        }
+
+        private static bool HandleMethodInvocation(SemanticModel semanticModel, AnonymousMethodExpressionSyntax anonymousMethod, ArgumentSyntax argumentSyntax, ImmutableDictionary<string, string>.Builder propertiesBuilder)
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1130UseLambdaSyntax.cs]: :bulb: It looks like `propertiesBuilder` is no longer used

Comment (vweijsters) [reply StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1130UseLambdaSyntax.cs]: Yes, I've missed that one. Its fixed now.
