### PR TITLE
Fixed issues in SA1135 for wrapped using statements

### LINKED ISSUE #2820: SA1135 reported for fully-qualified wrapped using directives
Currently SA1135 is incorrectly reported for the following code:

```csharp
using System;

namespace Test {
    using Example = System.ValueTuple<
        System.Exception,
        System.Exception>;
}
```

📝 I already wrote tests for this case, with the failing case marked as skipped, and will submit a PR for them shortly.

### PR DESCRIPTION
**Pull request by vweijsters**
Fixes #2820

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/Helpers/SymbolNameHelpers.cs [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+
+                AppendQualifiedSymbolName(builder, namedTypeSymbol);
+
+                if (namedTypeSymbol.IsGenericType)
+                {
+                    builder.Append(GenericTypeParametersOpen);
+
+                    foreach (var typeArgument in namedTypeSymbol.TypeArguments)
+                    {
+                        if (typeArgument is INamedTypeSymbol namedTypeArgument && typeArgument.IsTupleType())
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/Helpers/SymbolNameHelpers.cs]: 💡 I believe full coverage of this condition would need a test involving an array type as a generic type argument.

Comment (vweijsters) [reply StyleCop.Analyzers/StyleCop.Analyzers/Helpers/SymbolNameHelpers.cs]: I'll add that 👍
