### PR TITLE
Fixed indentation check issue where opening brace was always considered, even if it was…

### LINKED ISSUE #2774: SA1137 suggests wrong fixes
Updated to 1.1.0-beta009 (from 1.1.0-beta008)

We now have several violations on rule SA1137 (Elements should have the same indentation)

An example is:
``` csharp
private static Uri GetTemporarySharedReadAccessUri(ICloudBlob cloudBlob)
{
    var sasToken = cloudBlob.GetSharedAccessSignature(new SharedAccessBlobPolicy {
        Permissions = SharedAccessBlobPermissions.Read,
        SharedAccessExpiryTime = DateTimeOffset.UtcNow.AddHours(1),
        SharedAccessStartTime = DateTimeOffset.UtcNow.AddMinutes(-5) // mitigate clock skew
    });

    return new Uri($"{cloudBlob.Uri}{sasToken}");
}
```

When I apply the suggested fix I get:

``` csharp
private static Uri GetTemporarySharedReadAccessUri(ICloudBlob cloudBlob)
{
    var sasToken = cloudBlob.GetSharedAccessSignature(new SharedAccessBlobPolicy {
        Permissions = SharedAccessBlobPermissions.Read,
        SharedAccessExpiryTime = DateTimeOffset.UtcNow.AddHours(1),
        SharedAccessStartTime = DateTimeOffset.UtcNow.AddMinutes(-5) // mitigate clock skew
});

    return new Uri($"{cloudBlob.Uri}{sasToken}");
}
```

**Look for the moved `});` element.**

I could provide several different examples.

### PR DESCRIPTION
**Pull request by vweijsters**
…n't the first token on the line.

Fixes #2774

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1137ElementsShouldHaveTheSameIndentation.cs [hunk 1]
```diff
@@ -480,6 +480,12 @@ private static void CheckBraces(SyntaxNodeAnalysisContext context, SyntaxToken o
                 return;
             }
 
+            if (!openBraceToken.IsFirstInLine())
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1137ElementsShouldHaveTheSameIndentation.cs]: ❓ Should we still validate this, but validate it against the first token on the line containing the `{`?
