### PR TITLE
Naming CF refacture + two free code fixes

### LINKED ISSUE #173: Code fix: SA1300 (ElementMustBeginWithUpperCaseLetter)
Implement a code fix for #76.

### LINKED ISSUE #432: Code fix: SA1303 (ConstFieldNamesMustBeginWithUpperCaseLetter)
Implement a code fix for #79.

### PR DESCRIPTION
**Pull request by pdelvo**
Fixes #432
Fixes #173 

I created one code fix that fixes all diagnostics that require upper case symbols. With this I was able to have less code and we got code fixes for two diagnostics (SA1300 and SA1303) for free (almost).

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/NamingRules/RenameToUpperCaseCodeFixProvider.cs [hunk 1]
```diff
@@ -3,31 +3,35 @@
...
+    /// <para>To fix a violation of this rule, change the name of the symbol so that it begins with an upper-case letter,
+    /// or place the item within a <c>NativeMethods</c> class if appropriate.</para>
     /// </remarks>
-    [ExportCodeFixProvider(LanguageNames.CSharp, Name = nameof(SA1304SA1311CodeFixProvider))]
+    [ExportCodeFixProvider(LanguageNames.CSharp, Name = nameof(RenameToUpperCaseCodeFixProvider))]
     [Shared]
-    public class SA1304SA1311CodeFixProvider : CodeFixProvider
+    public class RenameToUpperCaseCodeFixProvider : CodeFixProvider
     {
         private const string Suffix = "Value";
```
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/NamingRules/RenameToUpperCaseCodeFixProvider.cs]: This suffix is not ideal for every case this CF is fixing now but I was not able to come up with a better one.

**Comment by pdelvo** [comment]
I just found a bug in both this CF and the analyzer for qualified names for namespaces. Im fixing this right now

**Comment by pdelvo** [comment]
I fixed the bug in the code fix provider. The bug in the analyzer might be a bug in roslyn that causes the HandleNamespaceDeclarationSyntax method to be called multiple times.
