### PR TITLE
Fix SA1200 UsingDirectivesMustBePlacedWithinNamespace

### LINKED ISSUE #383: Disable SA1200 if the file contains elements outside a namespace
Currently SA1200 is getting reported for files like **AssemblyInfo.cs**. If a file contains other elements outside a namespace, then SA1200 should be disabled for that file.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #383

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/SA1200UsingDirectivesMustBePlacedWithinNamespace.cs [hunk 1]
```diff
@@ -171,16 +172,48 @@ public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
...
+                case SyntaxKind.AttributeList:
+                    // suppress SA1200 if file contains an attribute in the global namespace
+                    return;
+
+                case SyntaxKind.UsingDirective:
+                    usingDirectives.Add(child);
+                    continue;
+
+                case SyntaxKind.ExternAliasDirective:
+                case SyntaxKind.NamespaceDeclaration:
```
Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/SA1200UsingDirectivesMustBePlacedWithinNamespace.cs]: These are unnecessary here

Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/SA1200UsingDirectivesMustBePlacedWithinNamespace.cs]: Since these items appear at the top level, I wanted to make sure the reader is aware that I didn't just forget to consider them.

Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/OrderingRules/SA1200UsingDirectivesMustBePlacedWithinNamespace.cs]: Okay. Looks good then :+1:
