### PR TITLE
Code fix for SA1009 with tests

### LINKED ISSUE #213: Code fix: SA1009 (ClosingParenthesisMustBeSpacedCorrectly)
Implement a code fix for #15.

### PR DESCRIPTION
**Pull request by Noryoko**
fixes #213

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1009ClosingParenthesisMustBeSpacedCorrectly.cs [hunk 1]
```diff
@@ -172,12 +183,18 @@ private static void HandleCloseParenToken(SyntaxTreeAnalysisContext context, Syn
                 if (!precedesStickyCharacter && !followedBySpace && !lastInLine)
                 {
                     // Closing parenthesis must{} be {followed} by a space.
-                    context.ReportDiagnostic(Diagnostic.Create(Descriptor, token.GetLocation(), string.Empty, "followed"));
+                    var properties = ImmutableDictionary.Create<string, string>()
```
Comment (Maxwe11) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1009ClosingParenthesisMustBeSpacedCorrectly.cs]: Why we create `ImmutableDictionary` and then mutate it?
`ToImmutableDictionary` extension also accepts `IEnumerable<KeyValuePair<,>` which implemented by `Dictionary<,>`

Comment (Maxwe11) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1009ClosingParenthesisMustBeSpacedCorrectly.cs]: looks cleaner
```c#
var properties = Dictionary<string, string>()
{
    [LocationKey] = LocationFollowing,
    [ActionKey] = ActionInsert
};
```
