### PR TITLE
SA1027 fix all provider and bug fixes

### LINKED ISSUE #1246: SA1027 (TabsMustNotBeUsed) code fix ignores trivia
e.g. assume all lines indented by tabs

		/// <summary>
		/// foo bar
		/// </summary>
		public void FooBar()

after code fix we will receive:

		/// <summary>
		/// foo bar
		/// </summary>
        public void FooBar()

code indented by spaces but documentation still indented by tabs

### LINKED ISSUE #1465: Implement a fix all provider for SA1027 (TabsMustNotBeUsed)
This diagnostic is still relying on the batch fixer. A custom fix all provider should be implemented for maximum efficiency in large solutions.

### PR DESCRIPTION
**Pull request by sharwell**
* Improved efficiency of SA1027 code fix by using text changes instead of trivia changes
* Fix analysis of comments; uses tests from @robinsedlaczek :+1: (Fixes #1246)
* Implement a custom fix all provider (Fixes #1465)

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1027CodeFixProvider.cs [hunk 1]
```diff
@@ -49,53 +49,84 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
-                SourceText sourceText = await document.GetTextAsync(cancellationToken).ConfigureAwait(false);
-                relevantText = sourceText.ToString(new TextSpan(violatingTrivia.FullSpan.Start - firstTriviaIndex, firstTriviaIndex + violatingTrivia.FullSpan.Length));
-            }
+        private static TextChange FixDiagnostic(IndentationOptions indentationOptions, SourceText sourceText, Diagnostic diagnostic)
+        {
+            TextSpan span = diagnostic.Location.SourceSpan;
 
+            TextLine startLine = sourceText.Lines.GetLineFromPosition(span.Start);
+            string text = sourceText.ToString(TextSpan.FromBounds(startLine.Start, span.End));
+            StringBuilder replacement = new StringBuilder();
```
Comment (Maxwe11) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1027CodeFixProvider.cs]: Why not to pass `text.Length` as capacity? I know that resulting string will be larger than `text.Length` but anyway it will reduce amount of SB chunks.

Comment (pdelvo) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1027CodeFixProvider.cs]: I dont think using a capacity that is too small in all possible cases (if the tab size is not set to 1) is a good idea. `indentationOptions.TabSize * text.Length` might be a good approximation.

This is only part of a code fix so not providing a capacity is not a big deal.

Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1027CodeFixProvider.cs]: I used `span.Length` instead of `text.Length`.

**Comment by Maxwe11** [comment]
:+1:
