### PR TITLE
Fix for bug in SA1115 (Parameter must begin on next line fix) #1886

### LINKED ISSUE #1886: SA1115 (Parameter must follow comma) generates diagnostic when parameter list contains #pragma directives
The following code generates a SA1115 diagnostic.

    public void Baz()
    {
        Bar(
    #pragma warning disable CS4014
            1,
    #pragma warning restore CS4014
            2);
    }

It shouldn't.

(The suppression here doesn't make sense, but it's common to use this particular suppression when intentionally not awaiting an async method.)

### PR DESCRIPTION
**Pull request by oatkins**
Fixes #1886.

### CODE REVIEW

**Comment by NikolayIT** [comment]
:+1: looks good to me

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1115ParameterMustFollowComma.cs [hunk 1]
```diff
@@ -327,6 +341,7 @@ private static bool IsValidTrivia(SyntaxTrivia trivia)
             case SyntaxKind.EndIfDirectiveTrivia:
             case SyntaxKind.DisabledTextTrivia:
             case SyntaxKind.WhitespaceTrivia:
+            case SyntaxKind.PragmaWarningDirectiveTrivia:
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1115ParameterMustFollowComma.cs]: :question: Is there any directive trivia we wouldn't want to consider here?

```csharp
if (trivia.IsDirective)
{
    return true;
}

switch (trivia.Kind())
{
...
}
```

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1115ParameterMustFollowComma.cs [hunk 2]
```diff
@@ -319,12 +333,13 @@ private static void AnalyzeParameterList(SyntaxNodeAnalysisContext context, Base
 
         private static bool IsValidTrivia(SyntaxTrivia trivia)
         {
+            if (trivia.IsDirective)
+            {
+                return true;
+            }
```
Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1115ParameterMustFollowComma.cs]: This check is probably not correct, as it will also mark `#region` / `#endregion` as valid, but I think they are not.

Comment (vweijsters) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1115ParameterMustFollowComma.cs]: It would be nice to have a test case for that as well.

Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1115ParameterMustFollowComma.cs]: :thought_balloon:  Those would still be reported as SA1123. I don't see any need to make a special consideration for it here as well.

**Comment by vweijsters** [comment]
I think this one is blocked until a decision has been made on how to proceeded with the other issues that I mentioned in #1886.

**Comment by vweijsters** [comment]
:+1:
