### PR TITLE
Removing an empty statement will no longer leave trailing whitespace

### LINKED ISSUE #1556: Removing empty statement should not leave trailing whitespace
Consider the following code, where the second `;` violates rule SA1106 (CodeMustNotContainEmptyStatements).

```csharp
throw new NotImplementedException(); ;
```

If the code fix for SA1106 is applied to this line, a trailing whitespace character remains on the line. This whitespace should be removed by the SA1106 code fix.

### PR DESCRIPTION
**Pull request by vweijsters**
Fixes #1556

### CODE REVIEW

File: StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1106CodeFixProvider.cs [hunk 1]
```diff
@@ -106,20 +106,39 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
-                TextChange textChange = new TextChange(line.SpanIncludingLineBreak, string.Empty);
+                textChange = new TextChange(line.SpanIncludingLineBreak, string.Empty);
                 return document.WithText(sourceText.WithChanges(textChange));
             }
+
+            TextSpan spanToRemove;
+            var whitespaceIndex = TriviaHelper.IndexOfTrailingWhitespace(token.LeadingTrivia);
+            if (whitespaceIndex >= 0)
+            {
+                spanToRemove = TextSpan.FromBounds(token.LeadingTrivia[whitespaceIndex].Span.Start, token.Span.End);
```
Comment (sharwell) [inline StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1106CodeFixProvider.cs]: :memo: As of fae34cb9e28926b0ebba73e1bfa6ba2c7cad03e2, no test is covering this line.

**Comment by vweijsters** [comment]
Updated after feedback

**Comment by sharwell** [comment]
:+1:
